### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by yutiya** [zhlynn/zsign#1]
./zsign -k sign.p12 -p xxx -m meoneAllAdHocProfile.mobileprovision -o output.ipa -b 'com.zoaosoft.xxx' -n 'NewWinBet' doubleH3lix-RC8.ipa
>>> Invalid Macho File (2)!
result is this？
I don't know?
can you help me?

**Comment by zhlynn** [comment]
i think your ipa file is broken, please check it.

**Comment by yutiya** [comment]
There is no problem executing the same command on MacOS.
The signed package can be installed on the iphone.

**Comment by zhlynn** [comment]
i have already tested it。
i found that, if you download doubleH3lix-RC8.ipa with wget command, the file is broken.
wget https://doubleh3lix.tihmstar.net/ipa/doubleH3lix-RC8.ipa

**Comment by yutiya** [comment]
B: yes. Thank you. I found something wrong with the wget download. I downloaded it in chrome
It was executed on Linux and MAC. The results are as follows
linux:
```
WriteFile: Failed in fopen! /tmp/zsign_folder_1568950026757229/Payload/doubleH3lix.app/_CodeSignature/CodeResources, No such file or directory
        Writing CodeResources Failed! /tmp/zsign_folder_1568950026757229/Payload/doubleH3lix.app/_CodeSignature/CodeResources
>>> Signed Failed! (0.141s, 141427us)
```
MacOS:
```
>>> Can't Find CodeSignature Segment!
>>> Realloc CodeSignature Space... 
>>> Success!
>>> Signed OK! (0.173s, 173182us)
```
_CodeSignature is not found.

**Comment by zhlynn** [comment]
Check whether the _CodeSignature folder exists？i created it before writing CodeResources file。
/tmp maybe is not a safe temp folder

**Comment by zhlynn** [comment]
or check unzip command。 i used unzip to release ipa file

**Comment by 245432007** [comment]
i have the same problem with macos.and my macos version is 10.15.2,macOS Catalina
>>> Invalid Macho File (2)!

**Comment by 245432007** [comment]
> Invalid Macho File (2)!
> i have the same problem with macOS and centOS.i had used unzip command to release ipa file.Then,i also download https://doubleh3lix.tihmstar.net/ipa/doubleH3lix-RC8.ipa,and use it to test,the same wrong result.I don't know why you are success but i'm fail.

Oh,sorry,my fault,i should use "./zsign -k privkey.pem -m dev.prov -o output.ipa -z 9 demo.ipa" to re-sign ipa,it success to me.Stupid me.

**Comment by 245432007** [comment]
> > Invalid Macho File (2)!
> > i have the same problem with macOS and centOS.i had used unzip command to release ipa file.Then,i also download https://doubleh3lix.tihmstar.net/ipa/doubleH3lix-RC8.ipa,and use it to test,the same wrong result.I don't know why you are success but i'm fail.
> 
> Oh,sorry,my fault,i should use "./zsign -k privkey.pem -m dev.prov -o output.ipa -z 9 demo.ipa" to re-sign ipa,it success to me.Stupid me.

But when i used zsign to change ipa's bundleid and bundle name,it still goes wrong.Invalid Macho File (2)!

**Comment by yonglam** [comment]
> B: yes. Thank you. I found something wrong with the wget download. I downloaded it in chrome
> It was executed on Linux and MAC. The results are as follows
> linux:
> 
> ```
> WriteFile: Failed in fopen! /tmp/zsign_folder_1568950026757229/Payload/doubleH3lix.app/_CodeSignature/CodeResources, No such file or directory
>         Writing CodeResources Failed! /tmp/zsign_folder_1568950026757229/Payload/doubleH3lix.app/_CodeSignature/CodeResources
> >>> Signed Failed! (0.141s, 141427us)
> ```
> 
> MacOS:
> 
> ```
> >>> Can't Find CodeSignature Segment!
> >>> Realloc CodeSignature Space... 
> >>> Success!
> >>> Signed OK! (0.173s, 173182us)
> ```
> 
> _CodeSignature is not found.
> macos signed ipa can be installed on the iphone.
> linux not.

Did you resolve this problem? :)

**Comment by nyuszika7h** [comment]
I have this issue with some IPAs too. Unzipping them and creating the `_CodeSignature` directory manually fixes it.
