### ISSUE TITLE
Can I use your tool as part of a commercial product ?

### ISSUE THREAD

**Issue by clementarnaudmicrofocuscom** [zhlynn/zsign#10]
To be clearer, do you have a licensing for this tool ?
Honestly, it is a great improvement compared to isign we were using before, so it would be good if we could use it :)

**Comment by robinchen** [comment]
我也想知道，你这个工具可以商用吗？还仅限个人学习

**Comment by zhlynn** [comment]
yes, it‘s free, but please mark the source of zsign in your product if possible.

**Comment by zhlynn** [comment]
i did not reference any isign code.

**Comment by clementarnaudmicrofocuscom** [comment]
Great !
In this case, it would be great if you just add in README by writing that your code is under license Apache2 or MIT.
