### ISSUE TITLE
Hello, the signature is really fast, but the compression is slow. Do you have any good solutions

### ISSUE THREAD

**Issue by xujimu** [zhlynn/zsign#102]

**Comment by gyke69** [comment]
Compression is totally depending on your system requirement. if you are using VPS and your compression is pretty slow make sure you upgrade your VPS RAM and CPU.

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
