### ISSUE TITLE
关于编译windows平台下的我遇到的报错问题解决

### ISSUE THREAD

**Issue by mayi2333** [zhlynn/zsign#103]
dirent.h这个头文件里面 DT_DIR 这个宏定义可能有问题
需要替换https://github.com/tronkko/dirent 这个项目里的头文件
然后 #include <sys/mman.h>
这里  这个sys这个路径会有问题，要去掉， 不知道是不是我一个人出这个错误
发在这里  给其他需要的朋友一个解决方案

**Comment by xujimu** [comment]
> dirent.h这个头文件里面DT_DIR这个宏定义可能有问题
> 需要替换https://github.com/tronkko/dirent这个项目里的头文件
> 然后#include <sys / mman.h>
> 这里这个sys这个路径会有问题，要去掉，不知道是不是我一个人出这个错误
> 发在这里给其他需要的朋友一个解决方案

您好,请问您编译成功了吗,可以发一份windows平台的二进制文件吗,我可以付费

**Comment by Upfunny** [comment]
同求win版zsign

**Comment by mayi2333** [comment]
需要编译好的留一下联系方式

**Comment by xujimu** [comment]
> 需要编译好的留一下联系方式

2524931333@qq.com 谢谢,请在邮箱里留一下支付宝,发个红包给您

**Comment by Upfunny** [comment]
80250282@qq.com 谢谢,请在邮箱里留一下支付宝,发个红包给您

**Comment by widuu** [comment]
windows must be modify path and modify some file to run this well

**Comment by hh-sign** [comment]
已经完成windows平台下的编译,以及界面版开发,需要的可以联系我探讨开发.

**Comment by wawo00** [comment]
> 需要编译好的留一下联系方式

能发我一下嘛，谢谢大佬，805413398@qq.com
