### ISSUE TITLE
CSSMERR_TP_NOT_TRUSTED In architecture: armv7

### ISSUE THREAD

**Issue by jayee347** [zhlynn/zsign#104]
苹果更新以后，当我新建 inhouse的 p12和mobileprovision之后。用zsign -k xxx.p12 -p 123456 -m xxx.mobileprovision -o xxxresgin.ipa xxx.ipa 签名。然而签名出来的xxxresign.ipa安装到ios设备上闪退。用codesign -v 验证签名提示 CSSMERR_TP_NOT_TRUSTED
In architecture: armv7
还是同一个p12和mobileprovision。 用codesign -fs 结果成功，并且成功在ios设备上运行。 codesing -v验证无报错。

**Comment by zhlynn** [comment]
inhouse is unsupported
