### ISSUE TITLE
How do I specify two `.mobileprovision` files?

### ISSUE THREAD

**Issue by JoslynWu** [zhlynn/zsign#11]
I have an app with extensions, I want to re-sign with a new account.
I specified `bundleid` and a `.mobileprovision`, but we can't be allowed to install.
The reason I found out was that the extended `.mobileprovision` was not modified.
Therefore, I would like to ask how to specify multiple (two) `.mobileprovision` (similar to the function of `fastlane sigh resign`)?

Thank you for your efficient and useful tools!

**Comment by zhlynn** [comment]
can you give me one demo ipa?

**Comment by JoslynWu** [comment]
I am very sorry, I am not convenient to provide a demo.

Can't install because I used mismatched `p12` and `. mobileprovision `.
After modifying the file, although the phenomenon I said still exists, it can be installed smoothly (other `.mobileprovision ` has been deleted), which is amazing.

**Comment by moul** [comment]
Hi @JoslynWu, I just opened #220 because I think that I'm facing a similar problem than yours

It would be very useful if you could give a look and let a feedback :+1: 

Thank you very much
