### ISSUE TITLE
sign special apps , apps crashed after installed signed ipa 

### ISSUE THREAD

**Issue by davidmdt21** [zhlynn/zsign#111]
first i want tell to Developer of Zsign , you are So Smart and great ,because your Script is the best for sign and install ipa on device ! 
now i have a problem with resign Apple Arcade game with zsign ... This is a very important and specialized topic . 

**when i resign a Apple arcade ipa file with zsign and install with them  on non jb device . game is crashed always** 

i research on google and i find for do  resign Apple Arcade ipa file  should  add app group  entitlements to provisioning profile  ! also One person told me : 
1) During provisioning profile generation, you need to create app group, then generate non-wildcard provisioning profile with that app group
2) during ipa resign, you need to edit every binary entitlements, so they will contain that group

so now i want to solve this problem . can you please help me for fix this issue  ? i think its very important question for every people !
thank you

**Comment by widuu** [comment]
I have encountered the same problem before, and it may exist in the directory__ MacOSX directory or. Dstore file. Or the plist file is unreadable. Generally speaking, all these problems will be solved by lifting them

**Comment by davidmdt21** [comment]
> I have encountered the same problem before, and it may exist in the directory__ MacOSX directory or. Dstore file. Or the plist file is unreadable. Generally speaking, all these problems will be solved by lifting them

thank for reply. but u do not understand about my problem ! zsign can`t sign any ipa file wich have entitlements 
my question is , how can i create or set some  entitlements on provisioning for sign with zsign . or zsign can inject some entitlements to ipa file after resigned ? 
you know , some apps for run need have some entitlements .  and thats why we have problem , after sign some ipa file with zsign and install to device , they apps can`t run and crashed . becuase They do not have the entitlements they needed 
so now any body understand my problem ? and any body can help to solve this important problem ?
notice : for example some Apple Arcade games after sign with zsign crashed .  

thank you

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
