### ISSUE TITLE
<Error>: Sandbox: AppName deny(1) file-write-unlink after resigning

### ISSUE THREAD

**Issue by ddzobov** [zhlynn/zsign#116]
App trying to download something and save it and i'm getting this error.

I found that adding com.apple.private.security.no-container entitlement can fix this issue.

So, my issue splits into two questions:
1) How can i fix this error (<Error>: Sandbox: AppName deny(1) file-write-unlink)?
2) How to use -e / --entitlements option (there is no info in docs about this)

**Comment by SigniOS** [comment]
zsign技术支持：
支持iOS15 iOS16的苹果签名工具
支持去除dylib动态库
完全免费，永久免费！
https://urlzs.com/44zCx
