### ISSUE TITLE
kernel AMFI: code signature validation failed.

### ISSUE THREAD

**Issue by hotsjf** [zhlynn/zsign#117]
Hey

I'm not sure if anyone else had this problem before.

I have a certificate which signing perfectly with codesign , but when I use zsign , the output IPA will crash on start. 
The error log shows:
`kernel	AMFI: code signature validation failed.`

Any insights would be greatly appreciated 
thanks

**Comment by AjithMuthusamy** [comment]
> Hey
> 
> I'm not sure if anyone else had this problem before.
> 
> I have a certificate which signing perfectly with codesign , but when I use zsign , the output IPA will crash on start.
> The error log shows:
> `kernel AMFI: code signature validation failed.`
> 
> Any insights would be greatly appreciated
> thanks

I am also facing the mentioned issue. Can you pls share me thee solution?
