### ISSUE TITLE
there is a question about ios14.3 ,can the author fix this question?

### ISSUE THREAD

**Issue by somethingeval** [zhlynn/zsign#118]
when i updated my iphone of the version ios14.3 ,i use the zsign to sign app and it alert a notice like this.  
![image](https://user-images.githubusercontent.com/77604041/104883135-3b083d80-599f-11eb-9393-2d73cca54eba.png)

**Comment by sbfkcel** [comment]
遇到同样的问题。

**Comment by sbfkcel** [comment]
https://github.com/zhlynn/zsign/pull/122

**Comment by oraoto** [comment]
@sbfkcel #122 也修复了这个问题吗？好像是不同的问题。

**Comment by sbfkcel** [comment]
> @sbfkcel #122 也修复了这个问题吗？好像是不同的问题。

使用 `codesign -dv xx.app` 查看版本号是得到了提升
