### ISSUE TITLE
Sign can’t support ios future

### ISSUE THREAD

**Issue by yugu91** [zhlynn/zsign#119]
See this page:
[Using the Latest Code Signature Format](https://developer.apple.com/documentation/xcode/using_the_latest_code_signature_format) 

App first open will be get a warning alert , Next iOS version will be not support.

Can fix?

**Comment by sbfkcel** [comment]
https://github.com/zhlynn/zsign/pull/122

**Comment by oraoto** [comment]
#122 is  probably unrelated to this issue, since it doesn't change the signature format.
