### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cooee** [zhlynn/zsign#12]
[root@test9527 zsign]# g++ *.cpp common/*.cpp -lcrypto -O3 -o zsign
/tmp/cc5mnqm7.o: In function `GenerateCMS(x509_st*, evp_pkey_st*, std::string const&, std::string const&, std::string&)':
openssl.cpp:(.text+0xe7): undefined reference to `OPENSSL_sk_new_null'
openssl.cpp:(.text+0xfe): undefined reference to `OPENSSL_sk_push'
openssl.cpp:(.text+0x113): undefined reference to `OPENSSL_sk_push'
/tmp/cc5mnqm7.o: In function `GetCMSContent(std::string const&, std::string&)':
openssl.cpp:(.text+0x431): undefined reference to `OPENSSL_die'
/tmp/cc5mnqm7.o: In function `ZSignAsset::GenerateCMS(std::string const&, std::string const&, std::string&)':
openssl.cpp:(.text+0xcd9): undefined reference to `OPENSSL_sk_new_null'
openssl.cpp:(.text+0xcf0): undefined reference to `OPENSSL_sk_push'
openssl.cpp:(.text+0xd05): undefined reference to `OPENSSL_sk_push'
/tmp/cc5mnqm7.o: In function `GetCertInfo(x509_st*, JValue&)':
openssl.cpp:(.text+0x1268): undefined reference to `X509_get_version'
openssl.cpp:(.text+0x138a): undefined reference to `X509_getm_notBefore'
openssl.cpp:(.text+0x13f5): undefined reference to `X509_getm_notAfter'
/tmp/cc5mnqm7.o: In function `GetCMSInfo(unsigned char*, unsigned int, JValue&)':
openssl.cpp:(.text+0x189b): undefined reference to `OPENSSL_sk_value'
openssl.cpp:(.text+0x18db): undefined reference to `OPENSSL_sk_num'
openssl.cpp:(.text+0x1901): undefined reference to `OPENSSL_sk_num'
openssl.cpp:(.text+0x1919): undefined reference to `OPENSSL_sk_value'
openssl.cpp:(.text+0x1c29): undefined reference to `OPENSSL_sk_num'
openssl.cpp:(.text+0x25fa): undefined reference to `OPENSSL_die'

i have yum install openssl-devel
but build error

**Comment by Rico358097990** [comment]
同样的问题，解决了吗
