### ISSUE TITLE
After re-signing, opening app crash.

### ISSUE THREAD

**Issue by zhuodream** [zhlynn/zsign#120]
Before January 28， the script is used normally in linux.
But todday, I get the error.

The Crash log is:
AMFI: '/private/var/containers/Bundle/Application/2B93AA2B-F8B8-4156-AEAA-8F8D7EC3342D/xxx.app/xx': Unrecoverable CT signature issue, bailing out.

And  I find Apple update the  wwdr certificate. 

[(https://developer.apple.com/support/wwdr-intermediate-certificate/ )]

Anyone know how to resolve the problem?

**Comment by oneword2018** [comment]
i don't know ,maybe i meet the same question

**Comment by dlz996** [comment]
I also have the same problem. If it is solved, could you please send an email to the email address: 422903005@qq.com
Thank you

**Comment by wochaowenya** [comment]
苹果更改了签名，Zsign是否会更新呢？

**Comment by oneword2018** [comment]
maybe it's not the reason of zsign



---Original---

**Comment by wochaowenya** [comment]
对的。好像是要修改服务器的配置。

**Comment by oraoto** [comment]
The certificate embedded in zsign source code should be renewed.

See: https://github.com/zhlynn/zsign/pull/122

**Comment by oneword2018** [comment]
> The certificate embedded in zsign source code should be renewed.
> 
> See: #122

can't understand it.

**Comment by zhuodream** [comment]
@oraoto Thank you. It worked!

**Comment by wochaowenya** [comment]
> @oraoto谢谢。有效！

我更新了证书，但是应用以然闪退。我用的centos的系统，

**Comment by oraoto** [comment]
@wochaowenya 是用旧的证书重签吗？可以到苹果后台删除掉，然后创建新的证书试试。

**Comment by oraoto** [comment]
@wochaowenya 苹果帐号里的证书是旧的吗？创建新的证书试一下。

**Comment by oraoto** [comment]
@wochaowenya https://developer.apple.com/account/resources/certificates/list 建新的证书，然后相关的 Provisioning Profile 也用新的试试。

**Comment by wochaowenya** [comment]
I tried, but failed. Maybe I made a mistake. Can you provide a stable contact, I hope to get your help, get more detailed information!

**Comment by chitantougangdi** [comment]
@wochaowenya  我也试了，但是不行，我有QQ1758334373，沟通

**Comment by pdso** [comment]
更新根证书，做新旧兼容。

**Comment by nyuszika7h** [comment]
Fixed in #129.
