### ISSUE TITLE
關於APP簽名後閃退問題解決方案

### ISSUE THREAD

**Issue by dlz996** [zhlynn/zsign#121]
需要替換服務器文件，以及衝簽名需要證書更新得到iOS14以後的版本，需要的聯繫Q：3417589542 ✈️：@GGB1930

**Comment by manopmaniphonh** [comment]
If you are willing to share your solution with me, please send an email to my mailbox: manopmaniphonh@outlook.com.Thx you

**Comment by oraoto** [comment]
See https://github.com/zhlynn/zsign/pull/122

**Comment by sbfkcel** [comment]
> See #122

COOL

**Comment by manopmaniphonh** [comment]
I update new WWDR certificate in openssl.cpp,I can sign and install ipa successful but application still crash when I open it.
Any other update?
________________________________
发件人: Oraoto <notifications@github.com>
发送时间: 2021年1月30日 9:29
收件人: zhlynn/zsign <zsign@noreply.github.com>
抄送: manopmaniphonh <manopmaniphonh@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [zhlynn/zsign] P於APP名後W退}解Q方案 (#121)


See #122<https://github.com/zhlynn/zsign/pull/122>

―

**Comment by oraoto** [comment]
@manopmaniphonh Dit you sign with an old developer certificate? Try create a new one at https://developer.apple.com/account/resources/certificates/list

**Comment by manopmaniphonh** [comment]
I don't konw my certficate is old or new,can you tell my how can create a new certificate?
________________________________
发件人: Oraoto <notifications@github.com>
发送时间: 2021年1月30日 13:52
收件人: zhlynn/zsign <zsign@noreply.github.com>
抄送: manopmaniphonh <manopmaniphonh@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [zhlynn/zsign] P於APP名後W退}解Q方案 (#121)


@manopmaniphonh<https://github.com/manopmaniphonh> Dit you sign with an old developer certificate? Try create a new one at https://developer.apple.com/account/resources/certificates/list

―

**Comment by killerpoio** [comment]
See #123
