### ISSUE TITLE
This is the latest zsign signature compiler

### ISSUE THREAD

**Issue by heiheiaakk** [zhlynn/zsign#124]
https://ws28.cn/f/4lhwd9fl31k

After the compilation of zsign, I heard that China's garbage is selling this. I now publish it for free

The effective time of the link is only 24 hours

**Comment by Alaa-Hany** [comment]
thank u it 's work 
is code open source ?

**Comment by Dershowitz011** [comment]
How to use this? What does it do?

**Comment by xujimu** [comment]
好人一胎十个

**Comment by Dershowitz011** [comment]
"Ten good people"?

What do you mean? Please tell the use of this and how to use it. Thanks.

**Comment by xujimu** [comment]
> 如何使用呢？它有什么作用？

Java open source project based on zsign
https://github.com/xujimu/ios_super_sign

**Comment by chitantougangdi** [comment]
你们谁知道，现在闪退的解决办法
