### ISSUE TITLE
关于iOS签名后闪退问题

### ISSUE THREAD

**Issue by chitantougangdi** [zhlynn/zsign#126]
已经去下载了苹果的CAG3证书进行替换软件里的证书
https://www.apple.com/certificateauthority/AppleRootCA-G3.cer

P8证书也是29添加的。但是仍然遇到安装后闪退。求解决方案
沟通方式 qq：1758334373

**Comment by chitantougangdi** [comment]
> 已经去下载了苹果的CAG3证书进行替换软件里的证书
> https://www.apple.com/certificateauthority/AppleRootCA-G3.cer
> 
> P8证书也是29添加的。但是仍然遇到安装后闪退。求解决方案
> 沟通方式 qq：1758334373

**Comment by nyuszika7h** [comment]
#129
