### ISSUE TITLE
Too large of singed ipa file

### ISSUE THREAD

**Issue by yugu91** [zhlynn/zsign#13]
Old ipa file is 18M,The singed ipa file is 51M,
And not work to from install

command: 
./zsign -k 111.p12 -p 12345 -m dd.mobileprovision -o output.ipa install.ipa

I can singed by fastlane this profile

**Comment by yugu91** [comment]
Sorry, It’s work, But still too large

**Comment by zhlynn** [comment]
-z 9

**Comment by yugu91** [comment]
it's perfect 😄
