### ISSUE TITLE
All apps are crashing 

### ISSUE THREAD

**Issue by gyke69** [zhlynn/zsign#134]
with the new update from the apple side all the application will crash " with new .p12 and .mobilerprovsion " although I have tried to update the zSign but so unfortunate the result is still the same! I request devs of zSign to look into this matter and solve the issue asap!

**Comment by agratoth** [comment]
Crash on iOS 14.5 beta?

**Comment by itaybia** [comment]
@gyke69 can you elaborate what the apple changes for the certificates/mobile-provisions are? is there some announcement from apple about this?

**Comment by agratoth** [comment]
@itaybia https://developer.apple.com/documentation/xcode/using_the_latest_code_signature_format

**Comment by itaybia** [comment]
@agratoth afaik zsign already does version 20400, so according to your link zsign should work fine.
