### ISSUE TITLE
签名后，闪退

### ISSUE THREAD

**Issue by robert98567** [zhlynn/zsign#137]
你好，请问在iOS14.2,14.3,14.4机器上，签名，打开闪退，如何解决，谢谢！

**Comment by plhwin** [comment]
zsign升级到最新

**Comment by robert98567** [comment]
升级到最新后，还是发现部分机型失败，iOS14.4

**Comment by robert98567** [comment]
> zsign升级到最新
升级到最新后，还是发现部分机型失败，iOS14.4

**Comment by williamyeung72** [comment]
zsign升级到最新 iOS14.3, 14.4 都會crash

**Comment by williamyeung72** [comment]
> > zsign升级到最新
> > 升级到最新后，还是发现部分机型失败，iOS14.4

有解決方法嗎?

**Comment by robert98567** [comment]
> > > zsign升级到最新
> > > 升级到最新后，还是发现部分机型失败，iOS14.4
> 
> 有解決方法嗎?

目前我们换了一个新账号，不闪退了，不确定是不是跟账号有关，同样的账号在其它设备就没问题

**Comment by robert98567** [comment]
> > > zsign升级到最新
> > > 升级到最新后，还是发现部分机型失败，iOS14.4
> 
> 有解決方法嗎?

暂时还没有
