### ISSUE TITLE
iOS 15 beta issue

### ISSUE THREAD

**Issue by gb160** [zhlynn/zsign#148]
Hi I'm unable to install any ipa signed with the latest zsign using the beta of iOS 15.

in the device log im finding this:

`0x16de0b000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 74: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.pW3TlU/extracted/Payload/My.app : 0xe8008029 (The code signature version is no longer supported.)`

Is this issue known? or does anyone know a way around this?

Just to point out, im using macOS, and ipas signed with iOS app signer work fine on iOS 15 beta.

Thanks.

**Comment by itcbx** [comment]
Can you please run the code on the app which signed by app signer and paste the output here
`codesign -dv xxxx.app`

**Comment by gb160** [comment]
> Can you please run the code on the app which signed by app signer and paste the output here
> `codesign -dv xxxx.app`

Sure...

`me@mbp ~/Desktop/ipas % codesign -dv /Users/me/Desktop/ipas/Payload/My.app 
Executable=/Users/me/Desktop/ipas/Payload/My.app/My
Identifier=com.me.my
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=798801 flags=0x0(none) hashes=24954+5 location=embedded
Signature size=4700
Signed Time=8 Jun 2021 at 15:18:44
Info.plist entries=64
TeamIdentifier=WKR69QA8B3
Sealed Resources version=2 rules=10 files=2540
Internal requirements count=1 size=180`

**Comment by scj643** [comment]
https://github.com/rileytestut/AltServer-Windows/commit/991070fbfb7a96af9fe3988517478516970202e3 Seems to be that the entitlements need to be added to the binary.

**Comment by Lee5533** [comment]
https://developer.apple.com/forums/thread/682775?page=2
it work to me.
