### ISSUE TITLE
iOS 15 not work

### ISSUE THREAD

**Issue by itcbx** [zhlynn/zsign#149]
when sign app with zsign on iOS 15, it says " The developer of this app needs to update it to work with this version of iOS", maybe the codesign in iOS 15 is changed.

**Comment by gb160** [comment]
Yes I have the same issue.

**Comment by davidmdt21** [comment]
hey , yes after i sign some apps with zsign and install on iOS 15 , its not work 
@zhlynn when will update for supporting ios 15 ? do you have any idea ?

**Comment by Xkinda** [comment]
try #151, it works for me

**Comment by h-o-sein** [comment]
> try #151, it works for me

What needs to be done to make it right?

**Comment by Xkinda** [comment]
> > try #151, it works for me
> 
> What needs to be done to make it right?
> What was the problem?

A DER Entitlement BLob (type 7, 0xfade7172) is required on iOS15. And it seems that the CMS Signature Blob should also be generated in another way after comparing with codesign

**Comment by chitantougangdi** [comment]
应该如何来纠正，遇到这个问题
