### ISSUE TITLE
ITMS-90426: Invalid Swift Support

### ISSUE THREAD

**Issue by sunhao-baikal** [zhlynn/zsign#150]
use zsign to resign  old.ipa （size 89.0M） to new.ipa （size 12.8M）,zsign shows archive ok !
then  i  transport new.ipa to itunes store via Transpoerter.
the app store connect says :ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit.

What went wrong?

**Comment by gyke69** [comment]
> use zsign to resign old.ipa （size 89.0M） to new.ipa （size 12.8M）,zsign shows archive ok !
> then i transport new.ipa to itunes store via Transpoerter.
> the app store connect says :ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit.
> 
> What went wrong?

there might be an issue with your ipa file, currently there is almost no issue with zSign.
