### ISSUE TITLE
App cannot be installed because its integrity could not be verified.

### ISSUE THREAD

**Issue by guthubah** [zhlynn/zsign#153]
I'm not entirely sure if this is caused by Zsign, but out of nowhere I'm suddenly getting this error when I install my signed apps.
Not every app/ipa has this issue.

I'm also using a paid developer certificate/account to sign my apps.

So far I've made several certificates and profiles and signed my apps with it, but I still get this error when installing them.

Edit:
I'm using Ubuntu
iOS 14.5

**Comment by gyke69** [comment]
> I'm not entirely sure if this is caused by Zsign, but out of nowhere I'm suddenly getting this error when I install my signed apps.
> Not every app/ipa has this issue.
> 
> I'm also using a paid developer certificate/account to sign my apps.
> 
> So far I've made several certificates and profiles and signed my apps with it, but I still get this error when installing them.
> 
> Edit:
> I'm using Ubuntu
> iOS 14.5

issue has been fixed with the lastest update zSign. please compile it again and resign your apps.

**Comment by zhlynn** [comment]
demo ipa

**Comment by guthubah** [comment]
Can confirm this issue has been resolved after updating zsign to the latest commit.

**Comment by gyke69** [comment]
> Can confirm this issue has been resolved for me after updating zsign to the latest.

Nope, still peeps keep getting error even with the new version.

I have got the old version and it is working pretty fine. Unfortunately latest still have the same issue

**Comment by ikool-cn** [comment]
Your Device + Certificate + BunnelID is block by Apple.
I have the same problem, everything is fine when I change other certificates.
