### ISSUE TITLE
Windows compiled version, and compilation tutorial, hope to help people in need

### ISSUE THREAD

**Issue by catfix2021** [zhlynn/zsign#158]
[zsign.zip](https://github.com/zhlynn/zsign/files/6847210/zsign.zip)
The above is the compiled windows exe program.
Thanks for the developer’s development, but the Windows compilation document is not detailed. I saw a lot of people asking in issues, and some people are paying for packaging programs. This is very excessive and very unfavorable for program sharing, so I want to share with me. The packaging process.
I referred to this tutorial, but it is not completely correct.
以上是编译好的windows exe程序。
感谢开发者的开发，不过windows编译文档不详。我看到很多人在问问题，有些人正在为打包程序付费。这是非常过分的，非常不利于程序共享，所以想和我分享打包过程。
我参考了这个教程，但它并不完全正确。
https : //blog.csdn.net/a513436535/article/details/108539238
First we prepare
Ubuntu-20.04.1
, I installed and deployed through vultr instead of making my own virtual machine in the tutorial. It usually only takes one to three minutes to create a server.
If you do not have a server account, please build a virtual machine yourself.
After logging in by default, you will be in the /root directory.
首先我们准备
Ubuntu-20.04.1
，我是通过vultr安装和部署的，而不是教程中自己制作虚拟机。创建服务器通常只需要一到三分钟。
如果没有服务器账号，请自行搭建虚拟机。
默认登录后，您将位于 /root 目录中。
1.安装mingw-w64，直接在终端模拟器上输入命令
1. Install mingw-w64 and enter commands directly on the terminal emulator

`sudo apt-get install mingw-w64`
2. install git
`sudo apt-get install git`
3.install make
`sudo apt-get install make`
4.git download zsing
`git clone https://github.com/zhlynn/zsign.git`
5.download openssl
`git clone https://github.com/openssl/openssl.git`
6.dwonload mman-win32
`git clone https://github.com/witwall/mman-win32.git`
7.download  dirent    ，The dirent project will help us fix a bug in the future
`git clone https://github.com/tronkko/dirent`

8. Compile the mman-win32 project
`cd /root/mman-win32`
`./configure --cross-prefix=x86_64-w64-mingw32-`
`make`
9.Compile the openssl 
`cd /root/openssl`
`git checkout OpenSSL_1_0_2s`
`./Configure --cross-compile-prefix=x86_64-w64-mingw32- mingw64`
In the official tutorial x86_64-w64-mingw32-, there is one missing ‘-’ symbol, so an error is reported here, so we can add it here again, and hope the author can modify it back.
`make`
10.Compile zsign project link to generate executable program under windows platform
请开始准备工作，修改
Please start the preparation work, modify
/root/zsign/common/common.h  
当前版本第七行 
The seventh line of the current version
`#include<mman.h>`
修改为 
change into
`#include</root/mman-win32/mman.h>`
然后到这个目录：
Then go to this directory:
`cd /root/dirent/include`
`The macro command of DT_DIR and the header file of struct dirent structure are also unique under Linux, so we need to modify it to
Implementation of the dirent.h header file under the win platform`
执行命令：
Excuting an order:
`sudo cp dirent.h /usr/share/mingw-w64/include`
11.现在，我们做好了所有的准备工作，开始打包程序
Now, we have done all the preparations and started packaging the program
`cd /root/zsign`

`x86_64-w64-mingw32-g++  \
*.cpp common/*.cpp -o zsign.exe -I../mman-win32 -I../openssl/include/ -L../openssl -L../mman-win32 -lmman -lcrypto -lgdi32 -std=c++11 -DWINDOWS -m64 -static-libgcc  -static-libstdc++
`

At this time, refresh the directory and you can see that the exe file has been generated. Thanks to the developers for their efforts, and hope to help those in need.
这时候刷新一下目录就可以看到exe文件已经生成了。

I have always been a cat, so I can only write so much.

**Comment by gyke69** [comment]
i don't know how to fix this solution, but it is really easy if you use it through ubuntu Operating system!

**Comment by xml520** [comment]
编译出来的exe 在windows10上无法使用

**Comment by SigniOS** [comment]
zsign技术支持：
支持iOS15 iOS16的苹果签名工具
支持去除dylib动态库
完全免费，永久免费！
https://urlzs.com/44zCx

**Comment by niuhuan** [comment]
我认为在windows的mingw环境下 ./configure --prefix=/mingw64 , 然后install就可以了。

如果非要使用临时目录， 可以新建一个文件夹，比如叫m1, 将mman重命名为system放进去

```
x86_64-w64-mingw32-g++  \
*.cpp common/*.cpp -o zsign.exe  \
-lcrypto -I../m1  \
-std=c++11  -I../openssl-master/include/  \
-DWINDOWS -L../openssl-master  \
-L../m1/sys  \
-lmman -lgdi32  \
-m64 -static -static-libgcc
```

**Comment by mega6453** [comment]
@catfix2021 I have created zsign.exe by following your steps. But it's not working.. It's not signing the ipa... and No error also. 

This is how I used =>    zsign.exe -k cert.pem -m test.mobileprovision -z 9 -o signedipa.ipa original.ipa

Can you please help?

**Comment by mega6453** [comment]
@zhlynn Can you help ?

**Comment by kryyyaaaa** [comment]
@mega6453 can you share zsign.exe file please

**Comment by mega6453** [comment]
@kryyyaaaa You can download from here...
[https://github.com/mega6453/AppiumWizard/raw/refs/heads/master/Appium%20Wizard/Resources/iOS/zsign.exe](https://github.com/mega6453/AppiumWizard/raw/refs/heads/master/Appium%20Wizard/Resources/iOS/zsign.exe)
