### ISSUE TITLE
Can't Get BundleID, BundleVersion, or BundleExecute in Info.plist! 

### ISSUE THREAD

**Issue by namesodiffcult** [zhlynn/zsign#160]
When i use  zsign，an error occurred like this, but  i use codesign under mac is no problem， help me please， thanks!
@zhlynn 

IPA File ：[http://152.32.216.5/demo.ipa](http://152.32.216.5/demo.ipa)
------------------------------------------------------
>>> Unzip:	/root/demo.ipa (324.86 MB) -> /tmp/zsign_folder_1626946685997109 ... 
>>> Unzip OK! (2.919s, 2919384us)
>>> Can't Get BundleID, BundleVersion, or BundleExecute in Info.plist! /tmp/zsign_folder_1626946685997109/Payload/xiangsuxiaojingling.app/SMPCQuickSDK.framework
>>> Signed Failed! (0.056s, 55825us)

**Comment by MartinLau7** [comment]
This is because `SMPCQuickSDK.framework` does not include the Info.plist file, which will be checked when Zsign signs.

**Comment by gyke69** [comment]
so i had the same problem. everytime zsign get update i clone it and save it.... 
for this exact mattter i use this version of zsign for linux and there is no error! 

here is the link - https://mega.nz/file/dQxU2LBA#bavf-fhjo2vxxk4rrQa5oBuG7P_AtL-sTk9tR-b5P1I

**Comment by zhlynn** [comment]
fixed

**Comment by gyke69** [comment]
> fixed

i can confirmed it is working pretty fine now! have test on more then 20 ipa which was giving error!
