### ISSUE TITLE
can you please fix this issue for linux users? Can't Get BundleID, BundleVersion, or BundleExecute in Info.plist!

### ISSUE THREAD

**Issue by gyke69** [zhlynn/zsign#162]
Can't Get BundleID, BundleVersion, or BundleExecute in Info.plist! /tmp/zsign_folder_1627186219155865/Payload/Spotify.app/Frameworks/CydiaSubstrate.framework

**Comment by zhlynn** [comment]
please give a demo ipa.

**Comment by gyke69** [comment]
> please give a demo ipa.

Dear @zhlynn , First of all i want to thank you for this amazing project. 
seems like after you saw i submitted issue you changed some codes and now it is working pretty fine. here are the changes 

https://prnt.sc/1g67vu6
https://prnt.sc/1g68brg
https://prnt.sc/1g68mub

Thank you for putting the effort and your time. 
###SOLVED

**Comment by gyke69** [comment]
#############SOLVED!!
