### ISSUE TITLE
App cannot be installed because its integrity could not be verified.

### ISSUE THREAD

**Issue by gyke69** [zhlynn/zsign#164]
this error is not for everyone, some people keep getting this error some doesn't for the same ipa. 
this error cause by apple black listing. @zhlynn could you kindly add anti-blacklist to " zSign" ? 

Thanks in advanced

**Comment by ikool-cn** [comment]
The app is running in a sandbox environment. I think there is no solution. If this problem occurs, you can only change the certificate. In other words, your certificate has been focused on by Apple.

**Comment by gyke69** [comment]
> The app is running in a sandbox environment. I think there is no solution. If this problem occurs, you can only change the certificate. In other words, your certificate has been focused on by Apple.

when i sign the applications using old version of zSign it works perfectly fine tho! so that being said totally it has to do with zSign. otherwise why the same application would work with older version of zSign and it does not work with the current version?

**Comment by ikool-cn** [comment]
Have you tried codesign under mac?

**Comment by gyke69** [comment]
> Have you tried codesign under mac?

difirrent codesign yes. zsign using mac no... i use zsign with a vps server

**Comment by ikool-cn** [comment]
Your problem is different with me. For the same certificate, some users can install it, some users cannot install it, 
tips "app cannot be verified" ,
but when I change the certificate, everything is ok.
