### ISSUE TITLE
Why only this app can't be installed on iPhone after resign?

### ISSUE THREAD

**Issue by hwreal** [zhlynn/zsign#167]
After resign [this app](https://github.com/JENJET/pac/raw/master/da.ipa), I try install to iPhone  by "itms-services://?action=download-manifest&url=manifest.plist" ,the iPhone console log:
 _**appstored:  Failing installation after receiving error: Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedDescription=This app could not be installed at this time., NSLocalizedFailureReason=Could not install at this time., NSLocalizedRecoverySuggestion=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.8GU6cB/extracted/Payload/DHD iOS.app : 0xe8008017 (A signed resource has been added, modified, or deleted.), NSUnderlyingError=0x102e74050 {Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.8GU6cB/extracted/Payload/DHD iOS.app : 0xe8008017 (A signed resource has been added, modified, or deleted.)" UserInfo={NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.8GU6cB/extracted/Payload/DHD iOS.app : 0xe8008017**_ 

But the resigned app can be installed directly by ios-deploy.  All iOS version have this problem, Is there something special about this app?

**Comment by gyke69** [comment]
Hello!
you are doing something wrong, i used the ipa file which you provided and signed it and then install on my iphone 6s plus iOS 14.3 and it is working pretty fine!

Signed - https://user-images.githubusercontent.com/58794647/129427433-ef862f5e-9e5a-454a-8b28-9dae8f6b24c8.png
App iCon - https://user-images.githubusercontent.com/58794647/129427297-b80315d6-de63-43f5-9bed-aee7d6e39b66.jpg
Splash - https://user-images.githubusercontent.com/58794647/129427298-08b1e7b4-bb69-4757-876b-b371c74d1f09.jpg

Check out screenshots!

**Comment by hwreal** [comment]
@gyke69 I guess you installed the resign APP by libimobiledevice? And I guess you also can't install by itms-service. My question is why only this app can't be installed by itms-service after resigned with zsign. However, it can be installed by itms-service after Mac's Codesign tool

**Comment by gyke69** [comment]
> @gyke69 I guess you installed the resign APP by libimobiledevice? And I guess you also can't install by itms-service. My question is why only this app can't be installed by itms-service after resigned with zsign. However, it can be installed by itms-service after Mac's Codesign tool

actually i have sign your app in Ubuntu 18.4 Vps server and i have installed it into my iDevice using example link 

itms-services://?action=download-manifest&url=https://yourwebsite.com/cdn/plist/yourapp.plist

so what you are saying is still incorrect this apps is working pretty fine after you codesign it with zSign. you can also install it with tms-service.

if you still have the same problem. please contact me  via telegram i might be able to help you way too quick.

**Comment by hwreal** [comment]
@gyke69 Thanks! I have find the cause of my problem. Because there is a "abc.DS_Store" file in ipa. Delete it or rename it to".DS_Store" will be OK. But I don't know why.

**Comment by gyke69** [comment]
> @gyke69 Thanks! I have find the cause of my problem. Because there is a "4d3e5a4b.DS_Store" file in ipa. Delete it or rename it to".DS_Store" will be OK. But I don't know why.

you are very welcome! kindly mark this issue as solved!

**Comment by SigniOS** [comment]
zsign技术支持：
支持iOS15 iOS16的苹果签名工具
支持去除dylib动态库
完全免费，永久免费！
https://urlzs.com/44zCx
