### ISSUE TITLE
injected framework is not properly signed

### ISSUE THREAD

**Issue by hotsjf** [zhlynn/zsign#168]
First thanks for this great work, it benefits the entire iOS community 

My issue is, I was trying to inject a Framework to the app, but after signing it, the actual framework binary is not signed properly 
When I verify its signature with codesign, the error was:
`main executable failed strict validation`

any idea?

**Comment by gyke69** [comment]
zSign doesn't inject frameworks it only injects dylib.

**Comment by hotsjf** [comment]
Any way to get around it? I’m not sure what’s the difference between dylib and frameworks

**Comment by gyke69** [comment]
> Any way to get around it? I’m not sure what’s the difference between dylib and frameworks
> […](#)
> On Aug 16, 2021, 11:41 PM -0400, gyke69 ***@***.***>, wrote: zSign doesn't inject frameworks it only injects dylib. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

https://github.com/Naituw/IPAPatch

**Comment by hotsjf** [comment]
thanks for the tip
