### ISSUE TITLE
 Can't Find Provision File! 

### ISSUE THREAD

**Issue by lingzhiyanna** [zhlynn/zsign#169]
使用 0.2 版本一切正常
换成 0.5的版本一直  Can't Find Provision File!
有遇到同样问题的么? 怎么解决 ?

**Comment by gyke69** [comment]
i am using the current version of zSign for my website and it is working perfectly fine. there is not such error as Can't find provision file. maybe you copied the provision file into wrong directory or you named the file different than what you command zsign.

**Comment by daisuke1227** [comment]
having the same problem heres my script  zsign -k /home/bauzadaisuke/certificate.p12 -p AppleP12.com -m /home/bauzadaisuke/m.mobileprovision -o output.ipa -b 'com.tree.new.bee' -n 'TreeNewBee' demo.ipa -k dev.p12 -p 123 -m dev.prov -o output.ipa -b 'com.tree.new.bee' -n 'TreeNewBee' demo.ipa
