### ISSUE TITLE
iOS 15.1 Developer Beta not work

### ISSUE THREAD

**Issue by Chertovski** [zhlynn/zsign#172]
after sign app with zsign on iOS 15.1 Developer beta 1 apps be crashed

**Comment by chengziqing** [comment]
me too,iOS 15 ，not work

**Comment by chengziqing** [comment]
update zsign ,is ok

**Comment by Chertovski** [comment]
> update zsign ,is ok

15.1 Developer Beta 1 ?

**Comment by gb160** [comment]
Not working for me on 15.1 beta.

**Comment by davidmdt21** [comment]
yes also  15.1 beta not work for me

**Comment by LetheCode** [comment]
15.1 beta not work, please update, thanks

**Comment by frankKiwi** [comment]
15.0(19A346) is not work.

**Comment by boxstore** [comment]
some issues. waiting for updates.
thanks to the contributors

**Comment by Tabstone** [comment]
Switches order of cdhashes so that cdhash 2 (SHA256) is first
