### ISSUE TITLE
签名很快，压缩很慢，请问下有优化方案吗？

### ISSUE THREAD

**Issue by chitantougangdi** [zhlynn/zsign#179]
>>> Unzip OK! (45.463s)
>>> Signed OK! (23.602s)
>>> Archive OK! (2.59 GB) (150.142s)
压缩花费了很多时间，有优化方案吗 谢谢！

**Comment by gyke69** [comment]
> Unzip OK! (45.463s)
> Signed OK! (23.602s)
> Archive OK! (2.59 GB) (150.142s)
> 压缩花费了很多时间，有优化方案吗 谢谢！

压缩完全取决于您的 PC / VPS / 或专用服务器的性能。例如，我使用“Contabo”VPS 服务器 XL VMe，3.5 GB 文件将在大约 44 秒内解压缩、签名、压缩。

**Comment by chitantougangdi** [comment]
> > 解压好！(45.463秒)签字同意！(23.602秒)存档正常！(2.59 GB)(150.142秒)压缩花费了很多时间,有优化方案吗 谢谢！
> 
> 压缩完全取决于您的PC / VPS /或专用服务器的性能。例如,我使用“康塔博”VPS服务器XL VMe，3.5 GB文件将在大约 44 秒内解压缩、签名、压缩。

我用的阿里服务器，运行中CPU占用很低，4核心CPU 签名时候占用仅仅25%  有没有办法让多个CPU同时工作

**Comment by chitantougangdi** [comment]
> > 解压好！(45.463秒)签字同意！(23.602秒)存档正常！(2.59 GB)(150.142秒)压缩花费了很多时间,有优化方案吗 谢谢！
> 
> 压缩完全取决于您的PC / VPS /或专用服务器的性能。例如,我使用“康塔博”VPS服务器XL VMe，3.5 GB文件将在大约 44 秒内解压缩、签名、压缩。

我用的阿里服务器，运行中CPU占用很低，4核心CPU 签名时候占用仅仅25%  有没有办法让多个CPU同时工作

**Comment by gyke69** [comment]
> > > 解压好！(45.463秒)签字同意！(23.602秒)存档正常！(2.59 GB)(150.142秒)压缩花费了很多时间,有优化方案吗 谢谢！
> > 
> > 
> > 压缩完全取决于您的PC / VPS /或专用服务器的性能。例如,我使用“康塔博”VPS服务器XL VMe，3.5 GB文件将在大约 44 秒内解压缩、签名、压缩。
> 
> 我用的阿里服务器，运行中CPU占用很低，4核心CPU 签名时候占用仅仅25% 有没有办法让多个CPU同时工作

我认为您必须与阿里巴巴服务器的支持人员交谈...看看他们可以为您做什么....但我的观点是Zsign在压缩解压缩和签署ipa文件时实际上非常好且快速。问题完全在于您的服务器速度！
