### ISSUE TITLE
Sign Failed ! when _CodeSignature dir is missing

### ISSUE THREAD

**Issue by ikool-cn** [zhlynn/zsign#181]
I am signed the same app, sometimes success, sometimes failed when _CodeSignature dir is missing.
only a few seconds before and after

>>> Unzip:	/root/game.ipa (16.77 MB) -> /tmp/zsign_folder_1632906722490211 ... 
>>> Unzip OK! (0.416s, 415858us)
>>> Signing: 	/tmp/zsign_folder_1632906722490211/Payload/quwanyouxi.app ...
>>> AppName: 	xxx
>>> BundleId: 	com.kepan.xxx
>>> BundleVer: 	1
>>> TeamId: 	xxx
>>> SubjectCN: 	iPhone Distribution: xxx
>>> ReadCache: 	NO
>>> SignFolder: Frameworks/DTCoreText.framework, (DTCoreText)
>>> SignFolder: Frameworks/EGUSDK.framework, (EGUSDK)
>>> Can't Find CodeSignature Segment!
>>> Realloc CodeSignature Space... 
>>> Success!
>>> SignFolder: Frameworks/DTFoundation.framework, (DTFoundation)
>>> SignFolder: Frameworks/EGameSDK.framework/Frameworks/DTCoreText.framework, (DTCoreText)
>>> SignFolder: Frameworks/EGameSDK.framework/Frameworks/DTFoundation.framework, (DTFoundation)
>>> SignFolder: Frameworks/EGameSDK.framework, (EGameSDK)
>>> SignFolder: quwanyouxi.app, (quwanyouxi)
>>> Signed OK! (0.658s, 657573us)
>>> Archiving: 	/root/game_signed.ipa ... 
>>> Archive OK! (16.94 MB) (5.962s, 5961777us)
>>> Done. (7.056s, 7056266us)

>>> Unzip:	/root/game.ipa (16.77 MB) -> /tmp/zsign_folder_1632906734448187 ... 
>>> Unzip OK! (0.417s, 416817us)
>>> Signing: 	/tmp/zsign_folder_1632906734448187/Payload/quwanyouxi.app ...
>>> AppName: 	xxx
>>> BundleId: 	com.xxx.xxx
>>> BundleVer: 	1
>>> TeamId: 	YNGS4XCZX3
>>> SubjectCN: 	iPhone Distribution: xxx
>>> ReadCache: 	NO
>>> SignFolder: Frameworks/DTCoreText.framework, (DTCoreText)
>>> SignFolder: Frameworks/EGUSDK.framework, (EGUSDK)
WriteFile: Failed in fopen! /tmp/zsign_folder_1632906734448187/Payload/quwanyouxi.app/Frameworks/EGUSDK.framework/_CodeSignature/CodeResources, No such file or directory
	Writing CodeResources Failed! /tmp/zsign_folder_1632906734448187/Payload/quwanyouxi.app/Frameworks/EGUSDK.framework/_CodeSignature/CodeResources
>>> Signed Failed! (0.035s, 34736us)
>>> Archiving: 	/root/game_signed.ipa ... 
>>> Archive OK! (16.72 MB) (5.941s, 5941102us)
>>> Done. (6.411s, 6410720us)

**Comment by ikool-cn** [comment]
My System Info

[root@localhost zsign-master]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@localhost zsign-master]# ll -lh
total 396K
-rw-r--r-- 1 root root  22K Jul 27 16:16 archo.cpp
-rw-r--r-- 1 root root 1.3K Jul 27 16:16 archo.h
-rw-r--r-- 1 root root  19K Jul 27 16:16 bundle.cpp
-rw-r--r-- 1 root root 1.2K Jul 27 16:16 bundle.h
drwxr-xr-x 2 root root  120 Jul 27 16:16 common
-rw-r--r-- 1 root root  350 Jul 27 16:16 Dockerfile
-rw-r--r-- 1 root root 7.3K Jul 27 16:16 macho.cpp
-rw-r--r-- 1 root root  720 Jul 27 16:16 macho.h
-rw-r--r-- 1 root root  21K Jul 27 16:16 openssl.cpp
-rw-r--r-- 1 root root  916 Jul 27 16:16 openssl.h
-rw-r--r-- 1 root root 5.5K Jul 27 16:16 README.md
-rw-r--r-- 1 root root  24K Jul 27 16:16 signing.cpp
-rw-r--r-- 1 root root 1.5K Jul 27 16:16 signing.h
-rw-r--r-- 1 root root 2.0K Jul 27 16:16 xmake.lua
-rwxr-xr-x 1 root root 252K Sep 29 16:49 zsign
-rw-r--r-- 1 root root 6.9K Jul 27 16:16 zsign.cpp
[root@localhost zsign-master]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@localhost zsign-master]# zsign -v
version: 0.5

**Comment by gyke69** [comment]
A new update has been pushed two days ago! Make sure you recompile zSign and sign you app again. It should work fine. Cheers

**Comment by ikool-cn** [comment]
Thanks ! @gyke69
