### ISSUE TITLE
cmake issues

### ISSUE THREAD

**Issue by hotsjf** [zhlynn/zsign#196]
Great work guys, thanks for keep this project updated so fast. 

a few things after changing to the CMake 

1. I believe there was another opened issue about this too. We got 'can't not file OPENSSL' errors after following the instruction.

2. the binary doubled in size.

3. I got error when loading some p12 files, I believe there might be some lib is missing ? Here is part of the error message
`Global default library context, Algorithm (RC2-40-CBC : 0)`

**Comment by gyke69** [comment]
You are right i just checked the "binary file it is double in size" after the compile is finished. 

screenshot cmake compile method - https://ibb.co/dpw8wmw

## Old method 
in the mean time you can use the old method to compile zsign which is! 

```console 
g++ *.cpp common/*.cpp -std=gnu++11 -lcrypto -O3 -o zsign
```
