### ISSUE TITLE
nject dylib and resign.

### ISSUE THREAD

**Issue by Jackliuchonghuan** [zhlynn/zsign#2]
Hello  I used this feature to open the IPA to see the verification signature information, and it appeared test.dylib: invalid signature (code or signature have been modified) .

**Comment by zhlynn** [comment]
i have fixed it, please update and try it again

**Comment by Jackliuchonghuan** [comment]
invalid Info.plist (plist or signature have been modified)

**Comment by Jackliuchonghuan** [comment]
./zsign -k dev.p12 -p 123 -m dev.prov -o output.ipa -l demo.dylib demo.ipa 
test.dylib: invalid Info.plist (plist or signature have been modified)

**Comment by Jackliuchonghuan** [comment]
./zsign -k dev.p12 -p 123 -m dev.prov -o output.ipa -l demo.dylib demo.ipa 
test.dylib: invalid Info.plist (plist or signature have been modified)

**Comment by Jackliuchonghuan** [comment]
test.dylib: invalid Info.plist (plist or signature have been modified)
Must this file be needed?

**Comment by zhlynn** [comment]
i don't have you dylib, but i think it has been fixed.  please update and try.  :)

**Comment by zhlynn** [comment]
> 
> 
> test.dylib: invalid Info.plist (plist or signature have been modified)
> Must this file be needed?

no

**Comment by Jackliuchonghuan** [comment]
yes fixed thank you!
