### ISSUE TITLE
The application does not have a valid signature on iOS 10.x

### ISSUE THREAD

**Issue by SeanXuCn** [zhlynn/zsign#203]
I'm using the latest commit.
An error will be reported on iOS10.x devices
"The application does not have a valid signature"

使用最新的commit在iOS10.x的设备上会报错，提示无效的签名。大佬有什么办法吗？

Installing 'com.xxx.wda.WDAMonitor'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: TakingInstallLock (20%)
Install: PreflightingApplication (30%)
Install: InstallingEmbeddedProfile (30%)
Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008019: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.4CsdjL/extracted/Payload/WDAMonitor.app : 0xe8008019 (The application does not have a valid signature.)

**Comment by gyke69** [comment]
> 
> 
> I'm using the latest commit.
> 
> An error will be reported on iOS10.x devices
> 
> "The application does not have a valid signature"
> 
> 
> 
> 使用最新的commit在iOS10.x的设备上会报错，提示无效的签名。大佬有什么办法吗？
> 
> 
> 
> Installing 'com.xxx.wda.WDAMonitor'
> 
> Install: CreatingStagingDirectory (5%)
> 
> Install: ExtractingPackage (15%)
> 
> Install: InspectingPackage (20%)
> 
> Install: TakingInstallLock (20%)
> 
> Install: PreflightingApplication (30%)
> 
> Install: InstallingEmbeddedProfile (30%)
> 
> Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008019: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.4CsdjL/extracted/Payload/WDAMonitor.app : 0xe8008019 (The application does not have a valid signature.)

Can you post a link for ipa? The specific ipa which you got error.

**Comment by Xkinda** [comment]
try #215

**Comment by SigniOS** [comment]
zsign技术支持：
支持iOS15 iOS16的苹果签名工具
支持去除dylib动态库
完全免费，永久免费！
https://urlzs.com/44zCx
