### ISSUE TITLE
Error When Run make/cmake

### ISSUE THREAD

**Issue by HaidarPhantom** [zhlynn/zsign#204]
Hello, after i install cmake and zlib libraries
and after make configuration and generate make files via cmake
when i run command make in terminal i have this error
 

```
 build make
[ 10%] Building CXX object CMakeFiles/zsign.dir/archo.cpp.o
[ 20%] Building CXX object CMakeFiles/zsign.dir/bundle.cpp.o
[ 30%] Building CXX object CMakeFiles/zsign.dir/macho.cpp.o
[ 40%] Building CXX object CMakeFiles/zsign.dir/openssl.cpp.o
/Users/XXX/Desktop/zsign-master/openssl.cpp:5:10: fatal error:
      'openssl/pem.h' file not found
#include <openssl/pem.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/zsign.dir/openssl.cpp.o] Error 1
make[1]: *** [CMakeFiles/zsign.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gyke69** [comment]
> > Are you using Mac or Linux?
> 
> 
> 
> Im using mac 

Open your terminal software and try following command, and complete the process. 

'''Bash
xcode-select --install 
'''

**Comment by HaidarPhantom** [comment]
> > > Are you using Mac or Linux?
> > 
> > 
> > Im using mac
> 
> Open your terminal software and try following command, and complete the process. Once it is finish, try to compile again. 😊
> 
> ```shell
> xcode-select --install
> ```

i already installed xcode when this error occured
