### ISSUE TITLE
Unable to import files into signed app with  zsign

### ISSUE THREAD

**Issue by SugarRayLua** [zhlynn/zsign#209]
Hello. I recently installed zsign on my Debian 10 Linux machine and really like its convenience. I was hoping it could help me resign the Jitterbug sideloaded iOS app and enable a special "VPN tunnel" function on that app that allows boot from the same device versus remotely. That special function requires the "Network Extensions" entitlement which I understand is only found on CustomMobileProvisions. All of the other signing apps (online or downloaded) either can't use CustomMobile Provisions, or if they can, when I use my CustomMobile Provision, it doesn't seem to sign the app in a correct way since the VPN tunnel doesn't work. Thankfully, zsign is the only resigner that I was able to use and get the VPN tunnel to work. Unfortunately, when I sign my .ipa app using zsign the app won't allow me import key support files to actually finishing running the app (the browser opens to let me pick the files to download but they don't download). Yet, all the other signers--although they don't allow me to use the VPN--do sign the .ipa in a way that lets me import the sort files into the app. //I'm trying to install the app on iPad OS 15 and am using resigning certificates purchased from UDID (Developer certificate and CustomMobileProvision). I'd appreciate any suggestions you might have; unfortunately, my Mac is also too old to run newer Xcode and the Xcode it does have doesn't sign iOS 15 .ipas. Thanks! :-

**Comment by SergeKZ** [comment]
> Hi! I just wanted to let you know that I figured out the problem and solution. In order for the entitlements to work, it turned out that I needed to change the bundle ID from the app I was signing to be the same as bundle ID from the Provisioning Profile I purchased (different bundle ID) using the -b flag when signing with zsign. I did that and it worked perfect, thanks! I'm going to recommend zsign to others in the community :-)


tell me how to do this?   example full command please

**Comment by gyke69** [comment]
> > Hi! I just wanted to let you know that I figured out the problem and solution. In order for the entitlements to work, it turned out that I needed to change the bundle ID from the app I was signing to be the same as bundle ID from the Provisioning Profile I purchased (different bundle ID) using the -b flag when signing with zsign. I did that and it worked perfect, thanks! I'm going to recommend zsign to others in the community :-)
> 
> tell me how to do this? example full command please

he basically says! check the bundleID inside the ipa file which you would like to sign. 
in order to check the bundleID extract the file file and then edit info.plist you will see the bundle ID in " CFbundleidentifer " 
use the "-b" command for zsign and specific that same bundleid after -b and sign your app, then it should work.

**Comment by orgserj** [comment]
> > > Hi! I just wanted to let you know that I figured out the problem and solution. In order for the entitlements to work, it turned out that I needed to change the bundle ID from the app I was signing to be the same as bundle ID from the Provisioning Profile I purchased (different bundle ID) using the -b flag when signing with zsign. I did that and it worked perfect, thanks! I'm going to recommend zsign to others in the community :-)
> > 
> > 
> > tell me how to do this? example full command please
> 
> he basically says! check the bundleID inside the ipa file which you would like to sign. in order to check the bundleID extract the file file and then edit info.plist you will see the bundle ID in " CFbundleidentifer " use the "-b" command for zsign and specific that same bundleid after -b and sign your app, then it should work.

Could it be related to deleting the cache 24 hours after installation !?

**Comment by orgserj** [comment]
> he basically says! check the bundleID inside the ipa file which you would like to sign.
> in order to check the bundleID extract the file file and then edit info.plist you will see the bundle ID in " CFbundleidentifer "
> use the "-b" command for zsign and specific that same bundleid after -b and sign your app, then it should work.

**zsign -k 1.p12 -p 123456 -m 1.mobileprovision -o good.ipa src.ipa -b com.panic.Prompt2**

import doesn't work anyway (

**Comment by gyke69** [comment]
> > he basically says! check the bundleID inside the ipa file which you would like to sign.
> > in order to check the bundleID extract the file file and then edit info.plist you will see the bundle ID in " CFbundleidentifer "
> > use the "-b" command for zsign and specific that same bundleid after -b and sign your app, then it should work.
> 
> he mentioned the Provisioning Profile! why?
> 
> **zsign -k 1.p12 -p 123456 -m 1.mobileprovision -o good.ipa src.ipa -b com.panic.Prompt2**
> 
> import doesn't work anyway (

if the app/game you want to sign it  requires app entitlement you wont be able to do it just by signing with its bundle ID, you need to create app entitlement in apple developer portal.

**Comment by orgserj** [comment]
> if the app/game you want to sign it requires app entitlement you wont be able to do it just by signing with its bundle ID, you need to create app entitlement in apple developer portal.

On iphone X ios 14 itorrent lets you import and export files!
On iphone 13 ios 15 = Error

**Comment by SugarRayLua** [comment]
Hi. I just saw everyone’s replies. Does anyone still need any further details on what I did to get zsign working well for my use? If so, happy to put some detail in this blog by the end of the week. Otherwise, good luck with itorrent and zsign :-)

**Comment by orgserj** [comment]
> Hi. I just saw everyone’s replies. Does anyone still need any further details on what I did to get zsign working well for my use? If so, happy to put some detail in this blog by the end of the week. Otherwise, good luck with itorrent and zsign :-)

We are waiting for your description

**Comment by gyke69** [comment]
> > if the app/game you want to sign it requires app entitlement you wont be able to do it just by signing with its bundle ID, you need to create app entitlement in apple developer portal.
> 
> 
> 
> On iphone X ios 14 itorrent lets you import and export files!
> 
> On iphone 13 ios 15 = Error

If you are able to sign itorrent and open it on an iPhone 13 , iOS 15! But you are not able to important and export files, that has nothing to do with zsign, itorrent developer needs to update their application.

**Comment by orgserj** [comment]
> Hi. I just saw everyone’s replies. Does anyone still need any further details on what I did to get zsign working well for my use? If so, happy to put some detail in this blog by the end of the week. Otherwise, good luck with itorrent and zsign :-)

write..))

**Comment by SugarRayLua** [comment]
Hi, @orgserj.
I don’t know what kind of app your are looking to use zsign to resign, but I needed it to resign the Jitterbug app which sideloads on my iPad and let me enable the iPad’s debugging JIT to speed up the performance of UTM, another sideloaded app port of the QEMU emulator that lets me run Linux as a guest on my iPad. Normally, the Jitterbug app is installed on another device (e.g. another iPad) and launches and then via wifi activates the JIT on the device running UTM. However, the Jitterbug/UTM developer built a feature into the Jitterbug app that now allows it to use VPN on the same machine as the UTM app to self-enable the JIT on the same device and not need a second device. However, in order to use the VPN feature, the app must be signed/re-signed with a mobile provision (in addition to a development certificate) to enable the Jitterbug app to use that self-tunneling VPN feature. I tried many app resigning services, but none of them allowed me to resign with the extra self-VPN “entitlement” so although the Jitterbug app would work, I couldn’t use the VPN feature and had to have a second device. Zsign, thankfully, was able to resign the Jitterbug app and in addition incorporate the “mobile provision” addition of the self-VPN feature. Thus, I’m not sure if you will need that extra mobile provision feature for the app you are trying to resign or not. If not, there are many other services that allow you to just resign an app with a development certificate but zsign seems just as fast if not faster (once installed and setup) than any of the resigning app sites. 

Here is an excerpt of the zsign use instructiions I posted on the issues Github page of the Jitterbug app for Jitterbug app users: 

Go to 'UDID Registrations' site & buy Platinum account ($20/yr). That gives you Paid Dev cert & custom profile (need the latter to get VPN working on same device).

Determine 'bundle id' of the custom profile you bought.

Download & install zhlynn/zsign linux signer (I put in linux in UTM).

Put cert & custom profile & downloaded Jitterbug.ipa in same folder.

CLI: zsign -k Cert.p12 -p password -m CustomProfile -o signed.ipa -b 'bundleIDnamefromcustomprofile' Jitterbug.ipa

Install signed.ipa on your device (I use https://diawi.com).

I hope that helps. Please let me know if you need more information about what I did. :-)

**Comment by orgserj** [comment]
> bundleIDnamefromcustomprofile

Thanks! I have a purchased certificate! where is the 'bundle id'? bundleIDnamefromcustomprofile

**Comment by SugarRayLua** [comment]
Hi, @orgserj. If you have a MAC, I found it easiest to go to the customprofile and right click and right click on it and choose “Get Info”. When you do that, at the bottom you will see a preview of multiple pieces of information about your customprofile including your “App ID”. Your customprofile’s bundle ID is just the App ID with all the characters before “com” removed (e.g. my App ID was XXXX.com.YYYY.explicit so the bundleID was just com.YYY.explicit”). I think though you only need to worry about the bundle ID if you are trying to resign an app with a custom profile that allows you to use special entitlements with the app (such as I needed to utilize the app’s VPN tunnel ability). I don’t think you need to use the bundleID for regular resigning of apps if you don’t need special entitlements from a custom profile. Hope that works for you :-)

**Comment by emranovin** [comment]
If you change app's bundle id to your provisioning profile's bundle id the app's push notification will stop working, won't it?
May I ask how could you resign app's Plugins with zsign? (I mean the Appex file format in Plugin folder)
Can you share your command?
@SugarRayLua

**Comment by SugarRayLua** [comment]
Hi, @emranovin. 

I very much apologize: I didn't document my steps well two years ago when I was using zsign as I should have, and now don't remember. I did try using zsign again a few months ago but couldn't remember enough of the steps again to get it to successfully sign my apps. Instead, now that I have an updated Mac desktop, i use iOS App signer which works well and would recommend using if you are able.

Sorry that I can't be more help; if you weren't already aware, zsign also has a discord channel where someone else may be able to help you. 

Have a good weekend. :-)

**Comment by emranovin** [comment]
No worries @SugarRayLua . Thanks anyway. I'll solve this and will share it with others.
 I didn't know there was such a thing. can you share the discord channel link?

**Comment by SugarRayLua** [comment]
Sure, @emranovin, here you go:

https://discord.gg/A4T6npnRCk

Good luck!

**Comment by emranovin** [comment]
Thank you @SugarRayLua but I guess this is not a channel for zsign repo. It's for this repo:
https://github.com/SignTools/SignTools

**Comment by SugarRayLua** [comment]
Sorry, @emranovin, I see I led you astray. I had that discord channel saved and thought it was for zsign, but then found my correspondence on it, and it seemed that instead I was trying out SignTools at the time and comparing it to zsign (and ended up using zsign instead). 

Hope that someone there is able to point you to someone who can answer your question.
