### ISSUE TITLE
ios 15.1 iphone 13 cache

### ISSUE THREAD

**Issue by SergeKZ** [zhlynn/zsign#217]
There is a problem with the application resetting the cache after a day. There is no such thing with a ios Signer (Mac)

**Comment by orgserj** [comment]
I confirm! The application cache is deleted 24 hours after installation

**Comment by davidmdt21** [comment]
Hello  Guys 

this problem  ( delet Cache apps after 1-2 day ) still  exist in iOS 15.2 ! 
this is so Bad problem ...
any body know to fix this ?

**Comment by davidmdt21** [comment]
anybody can help fix this problem ?? all apps after 24hours deleted cache and log out from account 
for example , when sign and install instagram rocket . after 24 hours account become log out

**Comment by orgserj** [comment]
> anybody can help fix this problem ?? all apps after 24hours deleted cache and log out from account for example , when sign and install instagram rocket . after 24 hours account become log out

Yes, in 15.2 the problem is relevant, there is no solution =(

**Comment by gyke69** [comment]
> anybody can help fix this problem ?? all apps after 24hours deleted cache and log out from account for example , when sign and install instagram rocket . after 24 hours account become log out

Hello,

Maybe try to sign all the iPA files using -f option zsign, and check the result. that might fix the issue since you sign them without iPA cache.

**Comment by orgserj** [comment]
> > anybody can help fix this problem ?? all apps after 24hours deleted cache and log out from account for example , when sign and install instagram rocket . after 24 hours account become log out
> 
> Hello,
> 
> Maybe try to sign all the iPA files using -f option zsign, and check the result. that might fix the issue since you sign them without iPA cache.

did not help =(

**Comment by orgserj** [comment]
> Hello Guys
> 
> this problem ( delet Cache apps after 1-2 day ) still exist in iOS 15.2 ! this is so Bad problem ... any body know to fix this ?

Did you manage to solve the problem?

**Comment by orgserj** [comment]
Updated to 15.3 now the cache is deleted every 7 days

**Comment by SigniOS** [comment]
zsign技术支持：
支持iOS15 iOS16的苹果签名工具
支持去除dylib动态库
完全免费，永久免费！
https://urlzs.com/44zCx
