### ISSUE TITLE
Add formal LICENSE file

### ISSUE THREAD

**Issue by fpotter** [zhlynn/zsign#22]
Excited to see this tool exists!  

Would you mind adding a formal LICENSE file to your repo?

Your README says _"zsign is completely free. Please mark the source of zsign in your commercial product if possible."_  Sounds like the MIT license would be a good candidate.

Looks like GitHub has a nice flow for adding licenses — https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by zhlynn** [comment]
thanks，i do not like any licenses.
