### ISSUE TITLE
The problem that IPA capacity is increased when SIGN

### ISSUE THREAD

**Issue by thmodz3320** [zhlynn/zsign#221]
How to fix the situation after signing done the IPA file increases in MB more than the original file
Example: Original Ipa 16MB - After SIGN 34MB

**Comment by gyke69** [comment]
> How to fix the situation after signing done the IPA file increases in MB more than the original file Example: Original Ipa 16MB - After SIGN 34MB

after you sign an ipa it is normal that its size is increase! you could you " -z 0-9 " option zsign decrease its size.

**Comment by boxstore** [comment]
-z 1

**Comment by gyke69** [comment]
> -z 1

-z 9
