### ISSUE TITLE
Latest commit broke support for iOS 15.0-15.1, but works on 15.2

### ISSUE THREAD

**Issue by iRayanKhan** [zhlynn/zsign#222]
Hello,

I am using the latest commit of zSign, and get the error "This app can't be installed, since its integrity can't be verified". 

I have tried two different developer accounts, 4 devices, and it seems to only install the app on 15.2 B2, and iOS 14.3. I haven't been able to get 15.0-15.0.2 to work on an iPhone, or 15.1 to work on an iPad. The latest commit may have made changes only for 15.1+ (iPhone), overriding the changes for 15.0-15.0.2.

It works on: 14.3 & 15.2
Doesn't work on: 15.0-15.0.2 (iPhone) and 15.1 (iPad)

If you need any more info from me, please let me know.

**Comment by thmodz3320** [comment]
I am also facing this problem without knowing the cause even though using the latest version of zsign

**Comment by iRayanKhan** [comment]
> I am also facing this problem without knowing the cause even though using the latest version of zsign

Older versions of zSign appear to work, the latest release may have overridden the commit for 15.0-15.1 support. @zhlynn is there a way you can make a fork of the previous commits?

**Comment by gyke69** [comment]
> > I am also facing this problem without knowing the cause even though using the latest version of zsign
> 
> 
> 
> Older versions of zSign appear to work, the latest release may have overridden the commit for 15.0-15.1 support. @zhlynn is there a way you can make a ~~fork~~ branch of the previous commits? 

If you are looking for it's compiled version of zsign I already have it in my repo, check me out. 

Ps: it's the previous version before the commit was made

**Comment by ivoidcat** [comment]
> > I am also facing this problem without knowing the cause even though using the latest version of zsign
> 
> Older versions of zSign appear to work, the latest release may have overridden the commit for 15.0-15.1 support. @zhlynn is there a way you can make a ~fork~ branch of the previous commits?

`git reset --hard 04d58f5e1502743f272a2a6b6acf098d95c1a43b`

**Comment by iRayanKhan** [comment]
> 

Which commit is the one that has working 15.0-15.1 support?

**Comment by gyke69** [comment]
> > 
> 
> 
> 
> Which commit is the one that has working 15.0-15.1 support? 

https://github.com/zhlynn/zsign/tree/11c1dbb3d075166eabb8cd4070659670930241a7

**Comment by ducanh2002123** [comment]
> > > 
> > 
> > 
> > Which commit is the one that has working 15.0-15.1 support?
> 
> https://github.com/zhlynn/zsign/tree/11c1dbb3d075166eabb8cd4070659670930241a7

it doesn't seem to be working for me, anyone else have any success using this commit?

**Comment by vkedwardli** [comment]
If #215 or #218 break my 15.1 support (#194), then you should use this commit:
https://github.com/zhlynn/zsign/tree/7ffc471bfc1602c092ba481ae18588f13e3f4c5a

**Comment by gyke69** [comment]
> If #215 or #218 break my 15.1 support (#194), then you should use this commit:
> 
> https://github.com/zhlynn/zsign/tree/7ffc471bfc1602c092ba481ae18588f13e3f4c5a

Well can you fix it? so the current version of yours support all of them

**Comment by vkedwardli** [comment]
@gyke69 Only if someone can provide a genuine signed IPA for me to diff

**Comment by gyke69** [comment]
> Hello,
> 
> I am using the latest commit of zSign, and get the error "This app can't be installed, since its integrity can't be verified".
> 
> I have tried two different developer accounts, 4 devices, and it seems to only install the app on 15.2 B2, and iOS 14.3. I haven't been able to get 15.0-15.0.2 to work on an iPhone, or 15.1 to work on an iPad. The latest commit may have made changes only for 15.1+ (iPhone), overriding the changes for 15.0-15.0.2.
> 
> It works on: 14.3 & 15.2 Doesn't work on: 15.0-15.0.2 (iPhone) and 15.1 (iPad)
> 
> If you need any more info from me, please let me know.

still facing this issue?

**Comment by iRayanKhan** [comment]
> > Hello,
> 
> > 
> 
> > I am using the latest commit of zSign, and get the error "This app can't be installed, since its integrity can't be verified".
> 
> > 
> 
> > I have tried two different developer accounts, 4 devices, and it seems to only install the app on 15.2 B2, and iOS 14.3. I haven't been able to get 15.0-15.0.2 to work on an iPhone, or 15.1 to work on an iPad. The latest commit may have made changes only for 15.1+ (iPhone), overriding the changes for 15.0-15.0.2.
> 
> > 
> 
> > It works on: 14.3 & 15.2 Doesn't work on: 15.0-15.0.2 (iPhone) and 15.1 (iPad)
> 
> > 
> 
> > If you need any more info from me, please let me know.
> 
> 
> 
> still facing this issue?
> 
> 

~~~~

Seems good for now, I'm still testing and will close this issue once I verify.

**Comment by gyke69** [comment]
Contact me in telegram regarding this issue!
@gyke69 👈 that’s I my tele
