### ISSUE TITLE
Unable to publish to appstore

### ISSUE THREAD

**Issue by q351941406** [zhlynn/zsign#223]
An upload error occurs when I use the Distribution certificate signature

ERROR ITMS-90034: "Missing or invalid signature. The bundle 'com.34rt555werwer10.com' at bundle path 'Payload/ducheng.app' is not signed using an Apple submission certificate."

Development can be installed and used

There is no problem with both certificates. I have tested them

**Comment by q351941406** [comment]
Identifier=com.34rt555werwer10.com
Format=app bundle with Mach-O universal (armv7 arm64)
CodeDirectory v=20400 size=17723 flags=0x0(none) hashes=543+7 location=embedded
Signature size=4818
Authority=(unavailable)
Info.plist=not bound
TeamIdentifier=6X3AJ82RVL
Sealed Resources version=2 rules=10 files=32
Internal requirements count=1 size=184



Authority is (unavailable),It's not normal

**Comment by xml520** [comment]
For the same problem, I found that the execution file was not modified after signing

**Comment by SigniOS** [comment]
zsign技术支持：
支持iOS15 iOS16的苹果签名工具
支持去除dylib动态库
完全免费，永久免费！
https://urlzs.com/44zCx

**Comment by q351941406** [comment]
Please do not close, this problem is not resolved

**Comment by sbfkcel** [comment]
the problem does exist

**Comment by redfearnk** [comment]
Yes, I have this problem also

**Comment by redfearnk** [comment]
I even used Apple's troubleshooting tool for this error: codesign --verify -vvvv -R='anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)' ~/Payload/MyApp.app

And all the checks came back as as successful, no problems detected
