### ISSUE TITLE
Does it suppourt below iOS 12 ?

### ISSUE THREAD

**Issue by aiOSFuture** [zhlynn/zsign#226]
![image](https://user-images.githubusercontent.com/16274705/146530926-76a4be37-111c-41ce-a3ad-436f738f9079.png)
iOS10

**Comment by gyke69** [comment]
> ![image](https://user-images.githubusercontent.com/16274705/146530926-76a4be37-111c-41ce-a3ad-436f738f9079.png) iOS10

iOS12+

**Comment by iRayanKhan** [comment]
Didn't a recent commit add iOS 10 support?

**Comment by iRayanKhan** [comment]
> > Didn't a recent commit add iOS 10 support? 
> 
> Not that I know of! 
> Zsign supports iOS 12+! 

https://github.com/zhlynn/zsign/pull/218

**Comment by gyke69** [comment]
There was a rollback in that commit.

**Comment by SigniOS** [comment]
zsign技术支持：
支持iOS15 iOS16的苹果签名工具
支持去除dylib动态库
完全免费，永久免费！
https://urlzs.com/44zCx
