### ISSUE TITLE
If the bundle ID contained hyphen, would singing zsign face problems?

### ISSUE THREAD

**Issue by kimiyazadeh** [zhlynn/zsign#227]
If the bundle ID contains hyphen, the zsing will not sing the app and the whole process will be failed.
According to the developer apple documentation archive, using hyphens is allowed.

"(Recommended) An identifier string that specifies the app type of the bundle. The string should be in reverse DNS format using only the Roman alphabet in upper and lower case (A–Z, a–z), the dot (“.”), and the hyphen (“-”). See CFBundleIdentifier for details."

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105

What solution do you propose?

**Comment by gyke69** [comment]
> If the bundle ID contains hyphen, the zsing will not sing the app and the whole process will be failed. According to the developer apple documentation archive, using hyphens is allowed.
> 
> "(Recommended) An identifier string that specifies the app type of the bundle. The string should be in reverse DNS format using only the Roman alphabet in upper and lower case (A–Z, a–z), the dot (“.”), and the hyphen (“-”). See CFBundleIdentifier for details."
> 
> https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105
> 
> What solution do you propose?

Hello, 

zsign can sign any type of bundle ID. here is the screenshot. 

https://prnt.sc/26mclnn
