### ISSUE TITLE
[Suggestion] Add support for injecting multiple dylibs at once

### ISSUE THREAD

**Issue by ducanh2002123** [zhlynn/zsign#228]
The title says it all I believe, but currently, there's only option to inject 1 dylib into the IPA file, and I would really want something that would allows me to put multiple dylib in at once instead of having to sign again and again for each dylib I want to inject

**Comment by gyke69** [comment]
> The title says it all I believe, but currently, there's only option to inject 1 dylib into the IPA file, and I would really want something that would allows me to put multiple dylib in at once instead of having to sign again and again for each dylib I want to inject

Hello, 
> You can do that simple by few line of bash script, i will provide you a sample down bellow.

```bash
#!/bin/sh
# Lets inject multiple ''dylibs'' into an ipa file.
# Path to your ipa file and make sure add ''dylibs'' in the same folder, in my case its in /root/ipa/ directory. 
 
cd /root/ipa/
for i in *.dylib ; do
/root/zsign -l $i "$i"
done 
echo "Dylibs has been injected successful."
exit
```

**Comment by ducanh2002123** [comment]
> > The title says it all I believe, but currently, there's only option to inject 1 dylib into the IPA file, and I would really want something that would allows me to put multiple dylib in at once instead of having to sign again and again for each dylib I want to inject
> 
> Hello,
> 
> > You can do that simply by few line of bash script, i will provide you a sample down bellow, change the paths according to your files.
> 
> ```shell
> #!/bin/sh
> # Lets inject multiple ''dylibs'' into an ipa file.
> # Path to your ipa file and make sure add ''dylibs'' in the same folder, in my case its in /root/ipa/ directory. 
>  
> cd /root/ipa/
> for i in *.dylib ; do
> /root/zsign -l $i "$i"
> done 
> echo "Dylibs has been injected successful."
> exit
> ```
> 
> > Result 👉 [Click me ](https://prnt.sc/26eaowe)

oh.. so the tl;dr version is that.. just use the -l argument multiple times?

**Comment by ducanh2002123** [comment]
> > The title says it all I believe, but currently, there's only option to inject 1 dylib into the IPA file, and I would really want something that would allows me to put multiple dylib in at once instead of having to sign again and again for each dylib I want to inject
> 
> Hello,
> 
> > You can do that simply by few line of bash script, i will provide you a sample down bellow, change the paths according to your files.
> 
> ```shell
> #!/bin/sh
> # Lets inject multiple ''dylibs'' into an ipa file.
> # Path to your ipa file and make sure add ''dylibs'' in the same folder, in my case its in /root/ipa/ directory. 
>  
> cd /root/ipa/
> for i in *.dylib ; do
> /root/zsign -l $i "$i"
> done 
> echo "Dylibs has been injected successful."
> exit
> ```
> 
> > Result 👉 [Click me ](https://prnt.sc/26eaowe)

oh.. so the tl;dr version is that.. just use the -l argument multiple times?

**Comment by gyke69** [comment]
> > > The title says it all I believe, but currently, there's only option to inject 1 dylib into the IPA file, and I would really want something that would allows me to put multiple dylib in at once instead of having to sign again and again for each dylib I want to inject
> 
> > 
> 
> > Hello,
> 
> > 
> 
> > > You can do that simply by few line of bash script, i will provide you a sample down bellow, change the paths according to your files.
> 
> > 
> 
> > ```shell
> 
> > #!/bin/sh
> 
> > # Lets inject multiple ''dylibs'' into an ipa file.
> 
> > # Path to your ipa file and make sure add ''dylibs'' in the same folder, in my case its in /root/ipa/ directory. 
> 
> >  
> 
> > cd /root/ipa/
> 
> > for i in *.dylib ; do
> 
> > /root/zsign -l $i "$i"
> 
> > done 
> 
> > echo "Dylibs has been injected successful."
> 
> > exit
> 
> > ```
> 
> > 
> 
> > > Result 👉 [Click me ](https://prnt.sc/26eaowe)
> 
> 
> 
> oh.. so the tl;dr version is that.. just use the -l argument multiple times?


Exactly! 

Kindly close this issues! 
Thanks

**Comment by gyke69** [comment]
@zhlynn this issue has been solved. Close it please.

**Comment by SigniOS** [comment]
zsign技术支持：
支持iOS15 iOS16的苹果签名工具
支持去除dylib动态库
完全免费，永久免费！
https://urlzs.com/44zCx
