### ISSUE TITLE
[1]    26942 segmentation fault, help

### ISSUE THREAD

**Issue by FOUNDERROR** [zhlynn/zsign#23]
>>> SignFolder: Frameworks
[1]    26942 segmentation fault

please hava  a look

**Comment by FOUNDERROR** [comment]
ZArchO::Init   >>> pLoadCommand += BO(plc->cmdsize);  
uint8_t  * pLoadCommand May Not Be Enough

**Comment by Tiny0529** [comment]
how to resolve?

**Comment by josiahhaswell** [comment]
Please include steps to reproduce
