### ISSUE TITLE
'openssl/pem.h' not found ... Help !!

### ISSUE THREAD

**Issue by HaidarPhantom** [zhlynn/zsign#235]
in mac 
Im trying to install zsign after after replacing openssl version 
g++ *.cpp common/*.cpp -lcrypto -I/usr/local/Cellar/openssl@x.x.x/include -L/usr/local/Cellar/openssl@x.x.x/lib -O3 -o zsign
this problem appears in terminal
```
openssl.cpp:5:10: fatal error: 'openssl/pem.h' file not found
#include <openssl/pem.h>
         ^~~~~~~~~~~~~~~
1 error generated.
common/common.cpp:6:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```
how to solve it ?

**Comment by redfearnk** [comment]
I ran into this when my paths to the lib and include directories (with the included version) was not correct. Once I fixed these paths, it worked:

`g++ *.cpp common/*.cpp -lcrypto -I/usr/local/Cellar/openssl@3/3.0.2/include -L/usr/local/Cellar/openssl@3/3.0.2/lib -O3 -o zsign`

**Comment by panderman** [comment]
It's ***.cpp**, not.cpp,Try it again

**Comment by HaidarPhantom** [comment]
> I ran into this when my paths to the lib and include directories (with the included version) was not correct. Once I fixed these paths, it worked:
> 
> `g++ *.cpp common/*.cpp -lcrypto -I/usr/local/Cellar/openssl@3/3.0.2/include -L/usr/local/Cellar/openssl@3/3.0.2/lib -O3 -o zsign`

thank you very much ,, it worked

**Comment by binnichtaktiv** [comment]
What I did was run 'brew info openssl' and then change the paths in the cmd. 
From 
'g++ *.cpp common/*.cpp -lcrypto -I/usr/local/Cellar/openssl@1.1/1.1.1k/include -L/usr/local/Cellar/openssl@1.1/1.1.1k/lib - O3 -o zsign'
 to 
'g++ *.cpp common/*.cpp -lcrypto -I/opt/homebrew/Cellar/openssl@3/3.2.1/include -L/opt/homebrew/Cellar/openssl@3/3.2 .1/lib -O3 -o zsign'
