### ISSUE TITLE
谁知道知舟的加速签咋个搞的

### ISSUE THREAD

**Issue by chitantougangdi** [zhlynn/zsign#238]
>>> 签名文件: 	../../data/tmp/zsign_folder_1647174378248139/Payload/IpaDownloadTool.app ...
>>> APP名称 : 	IPA下载器
>>> BundleId: 	cn.cydialmg.app
>>> TeamId: 	V9TUQC484P
>>> 证书名称   : 	iPhone Developer: Gabriel W Ransom (KBA77QFTZB)
>>> 加速签名: 	YES
>>> SignFile: 	timeLockDylib.dylib
>>> SignFolder: IpaDownloadTool.app, (IpaDownloadTool)
[32m>>> Signed OK! (0.014s, 14173us)
[0m>>> Done. (0.195s, 194725us)

**Comment by gyke69** [comment]
> 

could you be more specific about the issue you just opened? i might be able to help so kindly explain in details.

**Comment by chitantougangdi** [comment]
> > 
> 
> could you be more specific about the issue you just opened? i might be able to help so kindly explain in details.

hello，Please take a look at this. I packed a compression package.[https://wwi.lanzouy.com/iK82V01gfhdi
](https://wwi.lanzouy.com/iK82V01gfhdi)
