### ISSUE TITLE
[FR] Windows port

### ISSUE THREAD

**Issue by kotori2** [zhlynn/zsign#24]
I know there are something like WSL/Cygwin, i'm wondering if there is any possibility to add Windows support natively?

**Comment by MobilEKG** [comment]
Also, have the same question here.

**Comment by ddzobov** [comment]
You can run it under Docker. See readme.

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by kotori2** [comment]
@SigniOS 跑到人家issue里打广告，要不要点碧莲

**Comment by kotori2** [comment]
closed #68
