### ISSUE TITLE
Authority=(unavailable) 

### ISSUE THREAD

**Issue by gyke69** [zhlynn/zsign#241]
@XVilka @nyuszika7h @vkedwardli @trick77  @waruqi  @zhlynn @JosephShenton @josiahhaswell @ddzobov 

codesign -vv -d /Users/apple/Downloads/Payload\ 2/ducheng.app 
Executable=/Users/apple/Downloads/Payload 2/ducheng.app/ducheng
Identifier=com.657567retertqq1489
Format=app bundle with Mach-O universal (armv7 arm64)
CodeDirectory v=20400 size=17722 flags=0x0(none) hashes=543+7 location=embedded
Signature size=4807
Authority=(unavailable)
Info.plist=not bound
TeamIdentifier=KSN98Y9UBS
Sealed Resources version=2 rules=10 files=32
Internal requirements count=1 size=188

Authority=(unavailable)
when singing using zsign any idea why do i get that error above? i used fastlane and it works perfectly fine! i would appreciate any help!

**Comment by vkedwardli** [comment]
The above log doesn't look like it's from zsign for me

**Comment by gyke69** [comment]
> The above log doesn't look like it's from zsign for me

After i signed with zsign, i check its info with codesign apple codesign. i will provide screenshot of fastlane sign and result and zsign with its result! 

https://prnt.sc/WTtA7JQ07LSe  -  Fastlane < with codesign vv result you can see there is no error in authority 
https://prnt.sc/Uvc_F8KoGHZO  - zsign < with codesign vv you can see the error in authority.

because of my source code i need to sign the application i made with a linux app signer and then distributed in appstore.. and unfortunately its been more then 8 month i look for solution.

**Comment by vkedwardli** [comment]
The culprit should be from recent PRs, if you ignore all the recent commits and use the commit from my PR, it is showing the authority correctly

https://github.com/zhlynn/zsign/commit/602c3a0dd86a9bd7b5771a118cf31c3981fbb7d5

**Comment by gyke69** [comment]
> The culprit should be from recent PRs, if you ignore all the recent commits and use the commit from my PR, it is showing the authority correctly
> 
> [602c3a0](https://github.com/zhlynn/zsign/commit/602c3a0dd86a9bd7b5771a118cf31c3981fbb7d5)

Thank you so much, i will give it a try.

**Comment by gyke69** [comment]
> The culprit should be from recent PRs, if you ignore all the recent commits and use the commit from my PR, it is showing the authority correctly
> 
> [602c3a0](https://github.com/zhlynn/zsign/commit/602c3a0dd86a9bd7b5771a118cf31c3981fbb7d5)

the solution you suggested it worked perfectly fine. i use an old fork  compiled it and i have got the result which i expected. now my question is will zsign in the future remain broke or there is a possible fix? cause in some point we have to use the latest version of zsign and not face the issue which faced...

i used this fork - https://github.com/zhangjianxing2011/zsign

Thank you so much for the solution.

**Comment by gyke69** [comment]
> The culprit should be from recent PRs, if you ignore all the recent commits and use the commit from my PR, it is showing the authority correctly
> 
> [602c3a0](https://github.com/zhlynn/zsign/commit/602c3a0dd86a9bd7b5771a118cf31c3981fbb7d5)

ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/ducheng.app/ducheng' must be signed with the certificate that is contained in the provisioning profile."

now i encounter that issue.  however the authority shows this time.

**Comment by vkedwardli** [comment]
If someone can provide a valid Xcode signed binary, may be we can compare and update zsign
It's broken for a long time.

**Comment by q351941406** [comment]
[归档.zip](https://github.com/zhlynn/zsign/files/8322385/default.zip)
test.ipa uses ZSign
output.ipa uses Fastlane

@vkedwardli Please help us

**Comment by q351941406** [comment]
@vkedwardli This is my Telegram @iisjsbdvvdve ,Please contact me for more details

**Comment by vkedwardli** [comment]
@q351941406 is the Fastlane signed ipa the same as Xcode signed and is valid for uploading to the iTunes Connect?

**Comment by asasas222** [comment]
> @vkedwardli这是我的电报@iisjsbdvvdve，请联系我了解更多详情

你好，可以加下你的Q吗,有偿处理一下问题。

**Comment by DebianArch64** [comment]
This issue is now fixed in my fork https://github.com/DebianArch64/zsign

**Comment by DebianArch64** [comment]
Issue is caused in openssl.cpp file lines 212 is commented out and signer and pk is left NULL

Change
// CMS_add1_signer(cms, NULL, NULL, EVP_sha1(), nFlags);
To
CMS_add1_signer(cms, scert, spkey, EVP_sha1(), nFlags);

**Comment by gyke69** [comment]
> Issue is caused in openssl.cpp file lines 212 is commented out and signer and pk is left NULL
> 
> Change // CMS_add1_signer(cms, NULL, NULL, EVP_sha1(), nFlags); To CMS_add1_signer(cms, scert, spkey, EVP_sha1(), nFlags);

!solved
