### ISSUE TITLE
iphone 14 pro 不能安装

### ISSUE THREAD

**Issue by chengziqing** [zhlynn/zsign#265]
其他型号的iphone 升级到IOS 16都正常，只有14p的ios 16不能安装。估计是不是证书的问题？

**Comment by SunSoul** [comment]
请问下，我这边老手机升级到IOS16不能安装，是需要更新P12证书和.mobileprovision文件吗

**Comment by panderman** [comment]
证书和描述文件发下

**Comment by chengziqing** [comment]
找到解决方案了：
1、保证ipa上的id 与plist里的_id完全一致。
2、对于有些手机或14，升级到IOS16后，没有开发者模式的情况下，ＵＳＢ链接电脑使用iCareFone开启开发者模式。
