### ISSUE TITLE
it is not worked on Windows

### ISSUE THREAD

**Issue by WhyLogin** [zhlynn/zsign#285]
I get error message :
```
0xe8008029 (The code signature version is no longer supported.),
```

**Comment by niuhuan** [comment]
I can't run it on windows too. The zsign window closed quickly .

**Comment by zenochen** [comment]
you check the complied in https://github.com/isigner/iresign
I used it,  you can asked for source from the modifier.

**Comment by WhyLogin** [comment]
I have found it can not work because windows machines have stricter file locks.
So I refactored the relevant code
Then it worked
