### ISSUE TITLE
MacOS 下安装报错

### ISSUE THREAD

**Issue by ydbwwhq** [zhlynn/zsign#30]
g++ *.cpp common/*.cpp -lcrypto -I/usr/local/Cellar/openssl/1.0.2s/include -L/usr/local/Cellar/openssl/1.0.2s/lib -O3 -o zsign

clang: error: no such file or directory: '*.cpp'
clang: error: no such file or directory: 'common/*.cpp'

**Comment by wyxy2005** [comment]
去源码根目录执行...

**Comment by zhlynn** [comment]
more hands-on
