### ISSUE TITLE
openssl/provider.h: No such file or directory

### ISSUE THREAD

**Issue by qqizai** [zhlynn/zsign#315]
CentOS Linux release 7.9.2009 (Core)，
My openssl version is: 

```
[root@td zsign]# openssl version
OpenSSL 1.1.1t  7 Feb 2023
```

run ```./INSTALL.sh``` to compile zsign,  but get throw the errors：
```
openssl/provider.h: No such file or directory
 #include <openssl/provider.h>
                              ^
compilation terminated.
make[2]: *** [CMakeFiles/zsign.dir/openssl.cpp.o] Error 1
make[1]: *** [CMakeFiles/zsign.dir/all] Error 2
make: *** [all] Error 2
```

How should I deal with this error?

Thanks.

**Comment by qqizai** [comment]
I switch to this [commit ](https://github.com/zhlynn/zsign/commit/0510af8b499d7cdaf83e10e3dfa4cf0a92aac941)  and I can compile it successfully.

**Comment by Binkle** [comment]
> I switch to this [commit ](https://github.com/zhlynn/zsign/commit/0510af8b499d7cdaf83e10e3dfa4cf0a92aac941) and I can compile it successfully.

It's not work for me。

CentOS Linux release 7.9.2009 (Core)
OpenSSL 1.1.1t  7 Feb 2023

The same development environment.
