### ISSUE TITLE
-c args does not support .cer cert ？

### ISSUE THREAD

**Issue by ikool-cn** [zhlynn/zsign#32]
zsign -c /data/cert/test.cer -m /data/cert/test.prov -o /data/a_signed.ipa -z 9 /data/a.ipa
>>> Can't Load P12 or PrivateKey File! Please Input The Correct File And Password!

**Comment by zhlynn** [comment]
.cer does not contain the private key. you must use -k option

**Comment by ikool-cn** [comment]
I'm convert the cer to p12, everything is ok!
