### ISSUE TITLE
签名成功后，提示无法安装，

### ISSUE THREAD

**Issue by gitfornncn** [zhlynn/zsign#33]
>>> Signing: 	/xxxx/zsign/testbuld/xxxxx/Payload/Runner.app ...
>>> AppName: 	xxxxx
>>> BundleId: 	com.xxxx.xxxx
>>> TeamId: 	xxxxxx
>>> SubjectCN: 	iPhone Developer: xxx xxx xxx (TWxxxVFxxxxx)
>>> ReadCache: 	YES
>>> SignFolder: Frameworks/Reachability.framework, (Reachability)
>>> SignFolder: Frameworks/install_plugin.framework, (install_plugin)
>>> SignFolder: Frameworks/video_player.framework, (video_player)
>>> SignFolder: Frameworks/Flutter.framework, (Flutter)
>>> SignFolder: Frameworks/connectivity.framework, (connectivity)
>>> SignFolder: Frameworks/sqflite.framework, (sqflite)
>>> SignFolder: Frameworks/webview_flutter.framework, (webview_flutter)
>>> SignFolder: Frameworks/App.framework, (App)
>>> SignFolder: Frameworks/device_info.framework, (device_info)
>>> SignFolder: Frameworks/FMDB.framework, (FMDB)
>>> SignFolder: Frameworks/shared_preferences.framework, (shared_preferences)
>>> SignFolder: Frameworks/screen.framework, (screen)
>>> SignFolder: Frameworks/url_launcher.framework, (url_launcher)
>>> SignFolder: Frameworks/package_info.framework, (package_info)
>>> SignFolder: Frameworks/path_provider.framework, (path_provider)
>>> SignFile: 	Frameworks/libswiftObjectiveC.dylib
>>> SignFile: 	Frameworks/libswiftCore.dylib
>>> SignFile: 	Frameworks/libswiftCoreGraphics.dylib
>>> SignFile: 	Frameworks/libswiftDispatch.dylib
>>> SignFile: 	Frameworks/libswiftCoreFoundation.dylib
>>> SignFile: 	Frameworks/libswiftDarwin.dylib
>>> SignFile: 	Frameworks/libswiftFoundation.dylib
>>> SignFolder: Runner.app, (Runner)
>>> Signed OK! (0.309s, 309239us)
>>> Archiving: 	/www/xxxx/xxxxxx/output.ipa ... 
>>> Archive OK! (58.17 MB) (0.259s, 259127us)

zsign -k distribution.p12 -p xxxx -m kingfir_app_product.mobileprovision -z 9  -o output.ipa  gort/Payload/original.app

使用该命令签名的包都无法在手机上安装，下载完成之后图标变灰，然后提示“无法安装,请稍后再试”.
我的机型是 iphone sx max. 版本是13.1.2

**Comment by yswtrue** [comment]
会不会是证书和mobileprovision不对应或者证书不是生产证书

**Comment by gitfornncn** [comment]
> 会不会是证书和mobileprovision不对应或者证书不是生产证书

生产证书没用，反而是开发证书能编译安装。

**Comment by yswtrue** [comment]
> > 会不会是证书和mobileprovision不对应或者证书不是生产证书
> 
> 生产证书没用，反而是开发证书能编译安装。

我是要用生产证书才可以

**Comment by chinashehuiqiang** [comment]
是不是带framework的包？好像是有这个问题，或者闪退之类的，只能用其他替代方法，我已经解决了这个问题，交流可以加QQ群1084918361

**Comment by Adolf-L** [comment]
这个问题解决了吗？
