### ISSUE TITLE
How the cache work?

### ISSUE THREAD

**Issue by firstfan** [zhlynn/zsign#41]
I would like to know, if I sign the same app folder twice with different apple developer account, will the cache break the signing?

就说我看缓存加速应该就是把很多细碎文件的计算只算一次，记了下来，但我从代码看起来，这个缓存文件没有记录帐号信息，也就是说如果这时候我换一个帐号来，或者应该说是我换一个p12文件，用了缓存应该会导致签名出来的文件是坏的吧。
那cache的文件名里能不能包含下签名帐号或者key的信息呢，这样多帐号时候就不会混

**Comment by zhlynn** [comment]
it‘s not associated with the account or p12.

**Comment by firstfan** [comment]
Thanks. I will have a try.
