### ISSUE TITLE
can you have ideal to check certificate is die

### ISSUE THREAD

**Issue by jacken-deng** [zhlynn/zsign#43]
can you have ideal to check certificate is die

**Comment by zhlynn** [comment]
you can use openssl command to check certificate with ocsp protocol.
for example:
openssl ocsp -issuer issuefile -cert certfile -url ocspurl -header 'host' 'ocsphost' -resp_text -out outfile

**Comment by FOUNDERROR** [comment]
u can use https://snw-china.com/
support ipa p12 or mobileprovision

**Comment by jacken-deng** [comment]
> you can use openssl command to check certificate with ocsp protocol.
> for example:
> openssl ocsp -issuer issuefile -cert certfile -url ocspurl -header 'host' 'ocsphost' -resp_text -out outfile

can you give a demo to use it?

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
