### ISSUE TITLE
how to inject more than dylib

### ISSUE THREAD

**Issue by TweakyX** [zhlynn/zsign#46]
Hi @zhlynn ,

Thanks for this amazing tool , you saved my life

I wanna inject for example 4 dylibs each has it's own ".bundle" .. 
Could you please make it possible ..

Please and thank you

**Comment by zhlynn** [comment]
you'd better give me a demo ipa

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
