### ISSUE TITLE
Can't Find CodeSignature Segment

### ISSUE THREAD

**Issue by ikool-cn** [zhlynn/zsign#47]
I found a problem when the _CodeSignature directory is missing , Debug output like this

```
>>> SignFolder: Frameworks/DTCoreText.framework, (DTCoreText)
>>> SignFolder: Frameworks/EGUSDK.framework, (EGUSDK)
>>> Can't Find CodeSignature Segment!
>>> Realloc CodeSignature Space... 
>>> Success!
>>> SignFolder: Frameworks/DTFoundation.framework, (DTFoundation)
>>> SignFolder: Frameworks/EGameSDK.framework, (EGameSDK)
>>> SignFolder: arpg.app, (arpg)
>>> Signed OK! (0.713s, 713356us)
```
I can provide a test ipa package url, [http://suo.im/5KpUAM](http://suo.im/5KpUAM)
can you fix this problem? thank you!

**Comment by zhlynn** [comment]
you can use codesign to add it

**Comment by zhlynn** [comment]
it's just a tip

**Comment by ikool-cn** [comment]
but the app will crash

**Comment by roboticsexpert** [comment]
i have same problem ... if you need more ipa i can provide you so many

**Comment by chinashehuiqiang** [comment]
> I found a problem when the _CodeSignature directory is missing , Debug output like this
> 
> ```
> >>> SignFolder: Frameworks/DTCoreText.framework, (DTCoreText)
> >>> SignFolder: Frameworks/EGUSDK.framework, (EGUSDK)
> >>> Can't Find CodeSignature Segment!
> >>> Realloc CodeSignature Space... 
> >>> Success!
> >>> SignFolder: Frameworks/DTFoundation.framework, (DTFoundation)
> >>> SignFolder: Frameworks/EGameSDK.framework, (EGameSDK)
> >>> SignFolder: arpg.app, (arpg)
> >>> Signed OK! (0.713s, 713356us)
> ```
> 
> I can provide a test ipa package url, http://suo.im/5KpUAM
> can you fix this problem? thank you!

https://apple.supersigns.cn/dSJNNl I really  solve this problem

**Comment by undera** [comment]
DON'T CLICK ON LINK ABOVE!

Somebody should fix this malicious link. It was planted by hacker.
