### ISSUE TITLE
miss some signedAttrs

### ISSUE THREAD

**Issue by annidy** [zhlynn/zsign#5]
I found codesign add this attrs in der
```
            object: undefined (1.2.840.113635.100.9.2)
            value.set:
              SEQUENCE:
    0:d=0  hl=2 l=  45 cons: SEQUENCE
    2:d=1  hl=2 l=   9 prim:  OBJECT            :sha256
   13:d=1  hl=2 l=  32 prim:  OCTET STRING      [HEX DUMP]:2DFDDB4F882B71B4D25D04A5D7093EBF31D56B125CC5DEB088D63A750502E3A8

              SEQUENCE:
    0:d=0  hl=2 l=  29 cons: SEQUENCE
    2:d=1  hl=2 l=   5 prim:  OBJECT            :sha1
    9:d=1  hl=2 l=  20 prim:  OCTET STRING      [HEX DUMP]:60B7FCD16B82F8B3B1EB731801B89C6FE73990D6

            object: undefined (1.2.840.113635.100.9.1)
            value.set:
              OCTET STRING:
                0000 - 3c 3f 78 6d 6c 20 76 65-72 73 69 6f 6e   <?xml version

```
just before cdHashesPlist.

how did you think about it?

---

thank your for the great job 👏

**Comment by zhlynn** [comment]
i only build CODEDIRECTORY at version 0x20200. in that version. this attributes is not support(not verified).
in 0x20500 version, i found that attributes are sha1 of CSSLOT_CODEDIRECTORY, and sha256 of ALTERNATE_CODEDIRECTORY.

**Comment by annidy** [comment]
In 0x20400 version, has this attribute too.
Set CODEDIRECTORY at version 0x20200 can be acceptable, expect some app use codeLimit64 (rare)

**Comment by zhlynn** [comment]
need time to explore

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
