### ISSUE TITLE
How to make the resigned ipa receive the same push notification as the original ipa?

### ISSUE THREAD

**Issue by WuxiTianyiNetworkTechnology** [zhlynn/zsign#52]
When I resigned, I registered a new certificate and appid, opened the APNs function of the appid, and added a new APNs certificate. Then I created mobileprovision and signed the original ipa with the new appid, new mobileprovision, and new certificate. However, ipa cannot receive push notification after resignature.
I use other people's tools to achieve this function, but I don't know if zsign can achieve this function, please enlighten me.
thank you very much!

**Comment by SigniOS** [comment]
QQ多少 加一下17293449

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
