### ISSUE TITLE
Suppert version no argument?

### ISSUE THREAD

**Issue by jasonz1987** [zhlynn/zsign#54]
i want to use zsign for change my version no or build no in my ipa file ,is there any suggestion? @zhlynn

**Comment by yz-java** [comment]
you need to modify some of the source code(openssl library)

**Comment by yz-java** [comment]
> i want to use zsign for change my version no or build no in my ipa file ,is there any suggestion? @zhlynn

you need to modify some of the source code(openssl library)

**Comment by zhlynn** [comment]
modify Info.plist and then re-sign

**Comment by jasonz1987** [comment]
@zhlynn  the plist file on linux is not well formatly xml like mac. it doen't work  when i use sed command  in my bash script.
