### ISSUE TITLE
Question : Is this tool support older iOS versions?

### ISSUE THREAD

**Issue by boncheo** [zhlynn/zsign#6]
Please explain a bit about supporting range, iOS versions, Build Targets, CPU types and etc...

**Comment by zhlynn** [comment]
ios 11, ios 12, ios 13 tested.  arm64 an arm64e tested.  others are not tested. maybe you can help me to test more.

**Comment by Oisann** [comment]
I tested it on an iPhone 6(N61AP, iPhone 6 (GSM), iphoneos, arm64) running iOS 10.3.2 and it works.

**Comment by yugu91** [comment]
on iPhone 6s running IOS10.2 not work
