### ISSUE TITLE
Can we add homebrew support?

### ISSUE THREAD

**Issue by csc-EricWu** [zhlynn/zsign#64]

**Comment by Dershowitz011** [comment]
I absolutely second this. Please add Brew support. 

`$brew install zsign`

Such a marvellous thing where this will install all the correct and required dependencies. Please. I really hope this request will be obliged. Thanks.

**Comment by zhlynn** [comment]
good idea，i will do it when I am free.

**Comment by josiahhaswell** [comment]
#72

**Comment by zhlynn** [comment]
thanks

**Comment by csc-EricWu** [comment]
When can it be realized?

**Comment by csc-EricWu** [comment]
@zhlynn I hope you can see it.

**Comment by SoCuul** [comment]
Sorry for the necro, but is there a reason why this has not happened yet?
