### ISSUE TITLE
Can you please make a short video of "how to sign quickly"?

### ISSUE THREAD

**Issue by Dershowitz011** [zhlynn/zsign#70]
```
How to sign quickly?

You can unzip the ipa file at first, and then using zsign to sign folder with assets.
At the first time of sign, zsign will perform the complete signing and cache the signed info into .zsign_cache dir at the current path.
When you re-sign the folder with other assets next time, zsign will use the cache to accelerate the operation. Extremely fast! You can have a try！：）
```

A short video on this with the relevant command would to execute be fantastic. Do oblige. Thanks.

**Comment by zhlynn** [comment]
sorry，i have been very busy recently. In brief, you can have a look at .zsign_cache folder.

**Comment by Dershowitz011** [comment]
Where will I find the .zsign_cache folder? What is the command I must use to sign quickly? Thanks.

**Comment by zhlynn** [comment]
the folder in which zsign is currently executing.  it is a hidden folder.

**Comment by Dershowitz011** [comment]
Got it. Once that folder is there, I can use sign to directly sign them right? No need of unzipping them manually again?

**Comment by zhlynn** [comment]
yes, re-sign the same signed folder is fast.

**Comment by Dershowitz011** [comment]
Any particular command I should use?Please mention the correct command?
