### ISSUE TITLE
Use ZLIB/7Zip

### ISSUE THREAD

**Issue by josiahhaswell** [zhlynn/zsign#71]
Right now zsign doesn't quite work on Windows due to its dependence on the Zip utility.  I recommend compressing/uncompressing with ZLib.
https://zlib.net/zlib_how.html

This will also allow us to get rid of the platform-specific challenges of spawning a subprocess.

Also, my understanding (and I'm not very familiar with OSX bundling), is that a .app file is just an unarchived .ipa file.  Is that correct?  If so, I think we should add a command line to prevent archiving, thus generating a .app package.

If this sounds good, please feel free to assign this to me and I'll submit a PR

**Comment by zhlynn** [comment]
you are right, you can do it.

**Comment by josiahhaswell** [comment]
ZLib is actually quite difficult to use in this context as it doesn't support ZIP files specifically OOTB.  I have a prototype working the Poco ZIP which is substantially easier.  PR soon

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
