### ISSUE TITLE
Cross-platform releases

### ISSUE THREAD

**Issue by josiahhaswell** [zhlynn/zsign#72]
It would be helpful to release binaries for:
- [ ] Mac
- [ ] Linux
- [ ] Windows

Once the binaries are released, it should be straightforward to publish them to

- [ ] RedHat/CentOS (RPM)
- [ ] Homebrew
- [ ] Debian

Github actions is quite nice for this and provides access to MacOS containers.  Since Windows binaries can be built via MingW, this should be straightforward. 

@zhlynn I think that all distributed binaries should be statically linked to simplify distribution.  The statically linked Windows binary is 5.7 MB which I think is perfectly acceptable to avoid DLL hell.

**Comment by csc-EricWu** [comment]
We are looking forward to it

**Comment by csc-EricWu** [comment]
Is there any progress here?

@zhlynn @josiahhaswell

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
