### ISSUE TITLE
Can't Parse BundleExecute File!

### ISSUE THREAD

**Issue by sbfkcel** [zhlynn/zsign#78]
linux alpine

```bash
>>> SignFolder: lgjy.app, (lgjy)
>>> Can't Parse BundleExecute File! /test/Payload/lgjy.app/lgjy
>>> Signed Failed! (0.008s, 7884us)
>>> Archiving: 	/test.ipa ...
>>> Archive OK! (132.51 MB) (32.035s, 32035157us)
>>> Done. (32.055s, 32055382us)
```

Everything works fine on mac

alpine

Re-signing the xx.ipa file is also normal
Re-signing the xx.app directory throws the above exception

**Comment by Dershowitz011** [comment]
Kindly share the ipa. I'll try resigning. Thanks.

**Comment by sbfkcel** [comment]
[test.ipa.zip](https://github.com/zhlynn/zsign/files/4864638/test.ipa.zip)
I tried different ipa and it was all the same.

**Comment by Dershowitz011** [comment]
I'll try and update you now.

**Comment by sbfkcel** [comment]
Thank you

**Comment by Dershowitz011** [comment]
I could sign it just fine. I'll sign and give you if you can give your certificate and profile.

**Comment by sbfkcel** [comment]
thank.

I re-compressed the directory and signed it is OK, but there is this BUG under feedback.
