### ISSUE TITLE
Can't be install on iOS 14 beta3 after sign

### ISSUE THREAD

**Issue by ikool-cn** [zhlynn/zsign#84]
Maybe Apple changed the signature algorithm?

**Comment by IntZer0** [comment]
👍🏻

**Comment by JosephShenton** [comment]
iOS 14 b3 requires the CodeDirectory version to be updated.

iOS 14 requires a minimum CodeDirectory compatibility version of 0x00020400 to launch/install apps.

@zhlynn

**Comment by roboticsexpert** [comment]
i hope these helps you for fix this:

`[UPP2C3AB1D8/com.sibche.new] Notifing clients of the failed install with error: Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedDescription=This app could not be installed at this time., NSLocalizedFailureReason=Could not install at this time., NSLocalizedRecoverySuggestion=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXX.app : 0xe8008029 (The code signature version is no longer supported.), NSUnderlyingError=0x13089ded0 {Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXXX.app : 0xe8008029 (The code signature version is no longer supported.)" UserInfo={NSLocalizedDescription=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXXXX.app : 0xe8008029 (The code signature version is no longer sup`


for more information:
https://twitter.com/altstoreio/status/1286095962767728645?s=21

**Comment by JosephShenton** [comment]
https://github.com/zhlynn/zsign/pull/87
