### ISSUE TITLE
iOS14 mis-aligned LINKEDIT content 'code signature' (and possible fix)

### ISSUE THREAD

**Issue by itaybia** [zhlynn/zsign#86]
(Edited)
i've noticed that with some Frameworks, zsign didn't work. most seemed fine, but some had an alignment issue according to the runtime crash that was caused. specifically mine was a framework that was loaded at runtime by setting it as a dependent dylib.
seems like the Code Signature section wasn't aligned. this fix seemed to work:
`m_uCodeLength = uLength + 16 - (uLength % 16);`
inside the function `ZArchO::Init`

**Comment by killerpoio** [comment]
> seems like the Code Signature section isn't aligned. this fix seemed to work:
> `m_uCodeLength = uLength + 16 - (uLength % 16);`
> inside the function `ZArchO::Init`

Hello itaybia, I've tried to change this line of code, but it still can't install on iOS14, it can install on iOS13, Why?

**Comment by itaybia** [comment]
@killerpoio this isn't the only difference. if you'll notice, there's another change needed regarding the signature version (another opened issue in zsign). you should change the version value from 0x20200 to 0x20400. hopefully that will take care of whatever issue you have.

**Comment by killerpoio** [comment]
@itaybia It`s OK! Thank you very much!

**Comment by JosephShenton** [comment]
Fixed in #87

**Comment by itaybia** [comment]
@JosephShenton i think i had a bug. if alignement is not needed, no additional bytes should be added:

`	m_uCodeLength = (uLength % 16 == 0) ? uLength : uLength + 16 - (uLength % 16);`

**Comment by SigniOS** [comment]
Hello, what do you mean by the modified version number 0x20200? Thank you for your reply. It's very helpful to me. Thank you

**Comment by itaybia** [comment]
@SigniOS have a look at: https://github.com/zhlynn/zsign/pull/87/commits/7148dda8a6f3530ebcd84c4ca9597c4d2ef16916
ios14 apparently uses a different signing protocol version.

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx
