### ISSUE TITLE
NSURLSessionDownloadTask  cannot download file

### ISSUE THREAD

**Issue by allran** [zhlynn/zsign#90]
when use zsign to resign the app, I get follow error:
the download path file is not exist。

```
- (void)URLSession:(NSURLSession *)session downloadTask:(NSURLSessionDownloadTask *)downloadTask
                              didFinishDownloadingToURL:(NSURL *)location
{
    NSError *error = nil;
    NSString *path = location.path;
    BOOL isEx1 = [[NSFileManager defaultManager] fileExistsAtPath:path];

    dispatch_async(dispatch_get_main_queue(), ^{
        NSString *str = [NSString stringWithFormat:@"是否存在文件1：%i 位置:%@", isEx1, path];
        UIViewController *cuVc = [UIViewController topViewController];
        UIAlertController *alertVC = [UIAlertController alertControllerWithTitle:@"提示" message:str preferredStyle:UIAlertControllerStyleAlert];
        [alertVC addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) {}]];
        if (DeviceIsiPad() ) {
            alertVC.modalPresentationStyle = UIModalPresentationPopover;
            UIPopoverPresentationController *popPresenter = alertVC.popoverPresentationController;
            popPresenter.sourceView = cuVc.view;
            popPresenter.sourceRect = cuVc.view.bounds;
            [cuVc presentViewController:alertVC animated:YES completion:nil];
        } else
            [cuVc presentViewController:alertVC animated:YES completion:^{ }];
    });
}

then, the isEx1 is 0。
```

**Comment by Dershowitz011** [comment]
What's the command you used?

**Comment by allran** [comment]
1. load the zsign script:
brew install openssl
g++ *.cpp common/*.cpp -lcrypto -I/usr/local/Cellar/openssl@1.1/1.1.1g/include -L//usr/local/Cellar/openssl@1.1/1.1.1g/lib -O3 -o zsign

2. copy the zsign to target space.

3. resign the ipa file:
/Users/alan/PycharmProjects/ios_signature/scripts/zsign-osx -k /Users/alan/PycharmProjects/ios_signature/media/p12_files/china-263@msn.com/china263_dis.p12 -p 123456 -m /Users/alan/PycharmProjects/ios_signature/media/mobileprovision/testuser/comkailinKailinCollegecomkailinTqWvFbL9P65Z.mobileprovision -o /Users/alan/PycharmProjects/ios_signature/media/download_files/testuser/KailinCollege_8hDRtLD_8.ipa /Users/alan/PycharmProjects/ios_signature/media/ipa_files/testuser/KailinCollege_M7YSi3f.ipa

4. use the resign file to install at iPhone.

**Comment by allran** [comment]
When I use KailinCollege_M7YSi3f.ipa to install at iPhone,  I can download file.
then, I use the resign file of KailinCollege_8hDRtLD_8.ipa  to install at iPhone, I can't download file. Because the location.path is not exist file。
