### ISSUE TITLE
Give me the windows binary please ,please

### ISSUE THREAD

**Issue by John0King** [zhlynn/zsign#91]
I need the binary for windows and mac , so I can P/Invoke this app  or calling this app  with C# ,    but how do I get the binary ?
I try to build my self on Windows with Visual studio 2019 ,  but it has so many  `#include xxxx`  error
----------------------
I try to build using wsl2 centos, debian, ubuntu ,   and I stuck on the first step :  `apt-get install mingw-w64 `  😭

**Comment by xujimu** [comment]
Me too. Have you solved it

**Comment by John0King** [comment]
no,  I wasn't,

**Comment by CrafterPika** [comment]
Here:
[zsign-win32.zip](https://github.com/zhlynn/zsign/files/6909927/zsign-win32.zip)

**it won't work tho** due to a windows path error (see #113, and the fork is not up-to-date), **and no compiling yourself won’t fix it**

the mistake you made is in [this line](https://github.com/zhlynn/zsign/blob/master/common/common.h#L7) 
you didn’t change `#include <sys/mman.h>` to `#include <mman.h>`

**Comment by long51xy** [comment]
> Here:
> [zsign-win32.zip](https://github.com/zhlynn/zsign/files/6909927/zsign-win32.zip)
> 
> **it won't work tho** due to a windows path error (see #113, and the fork is not up-to-date), **and no compiling yourself won’t fix it**
> 
> > but it has so many #include xxxx error
> 
> the mistake you made is in [this line](https://github.com/zhlynn/zsign/blob/master/common/common.h#L7)
> you didn’t change `#include <sys/mman.h>` to `#include <mman.h>`
> 
> > I try to build using wsl2 centos, debian, ubuntu , and I stuck on the first step : apt-get install mingw-w64 😭
> 
> Learn to use linux:
> 
> * Centos does not have `apt`, it’s `yum`
> * Debian and Ubuntu need `sudo` before apt (`sudo apt-get install mingw-w64`)

Does the implementation run under Windows

**Comment by CrafterPika** [comment]
> Does the implementation run under Windows?

 Have you read my message?
 > **it won't work tho** due to a windows path error (see #113, and the fork is not up-to-date), **and no compiling yourself won’t fix it**

The program sure does run under windows.
But **you cannot sign a single app** due to the windows path error.
