### ISSUE TITLE
centos7 report this error

### ISSUE THREAD

**Issue by okada8** [zhlynn/zsign#92]
error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

**Comment by adelezzatl** [comment]
i fixed it by adding "-std=c++11 " flag.
sudo g++ *.cpp common/*.cpp -lcrypto -O3 -std=c++11 -o zsign
