### ISSUE TITLE
Can't Find App Folder!

### ISSUE THREAD

**Issue by xujimu** [zhlynn/zsign#96]
But he does exist

[root@www tmp]# zsign -k /sign/temp/123/cert/da1a8314-e03a-4a39-afb3-d788e24dcc24/p12.p12 -p 123456 -m /sign/mode/temp/1598621527188.mobileprovision -o /sign/mode/temp/1598621527209.ipa  /sign/temp/123/distribute/1/1.ipa
>>> Unzip:	/sign/temp/123/distribute/1/1.ipa (15.55 MB) -> /tmp/zsign_folder_1598622362395643 ... 
>>> Unzip OK! (0.706s, 706097us)
>>> Can't Find App Folder! /tmp/zsign_folder_1598622362395643
>>> Signed Failed! (0.000s, 58us)
>>> Can't Find Payload Directory!

![image](https://user-images.githubusercontent.com/61351674/91573178-6bf8bf00-e979-11ea-8261-aedead849307.png)

**Comment by reheroad** [comment]
我也遇到了这个问题，你解决了吗？
